// test header
// Code generated by cmd/gentypes; DO NOT EDIT.

export type Kind = "a" | "b";

export interface inner {
  n: number;
  tags?: Record<string, number>;
  pair: [number, number];
  raw: unknown;
}

export interface outer {
  id: number;
  name?: string;
  flag: boolean;
  inner: inner;
  inners: inner[];
  maybe_n: number | null;
  kind: string;
  bytes: string;
  any: unknown;
  optional?: inner | null;
}
