package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/adams-shaun/gorge/cards"
	"github.com/adams-shaun/gorge/effects"
)

// The coverage command writes the card-support overview the repository
// publishes on GitHub: docs/coverage.md in full, plus a summary table spliced
// into README.md between the two markers below.
//
// WHY THE TABLE IS NOT BY SET. Forge's card scripts carry no set or edition
// data at all — a script is one card's behaviour, printed-set-agnostic, which
// is exactly why gorge can compile them without shipping them. Set membership
// lives in a different Forge tree (forge-gui/res/editions), which is GPL-3.0
// like the rest and which `forgec fetch` deliberately does not pull: adding it
// would double the fetched corpus and add a second GPL dependency for a
// cosmetic axis. So the breakdown groups by the three things the compiled IR
// does carry and that a reader actually wants: card type, colour and mana
// value. Card type is the useful one — it tracks which engine subsystems are
// done — and the other two are there to show the gap is not concentrated in
// one colour or at one end of the curve.
//
// The output is deterministic: no wall clock anywhere, every table sorted,
// and the only identifier printed is the corpus commit the measurement ran
// against. Deliberately NOT printed: the gorge commit being measured. Stamping
// it would change the file on every push, so the refresh job would commit on
// every push and `-check` would be stale the moment anything else landed.
// Re-running over an unchanged corpus and tree reproduces the file byte for
// byte, so the refresh job commits nothing when nothing moved.
const (
	readmeBeginMarker = "<!-- BEGIN COVERAGE -->"
	readmeEndMarker   = "<!-- END COVERAGE -->"
)

// topMissingInDoc is how many unimplemented primitives docs/coverage.md ranks.
const topMissingInDoc = 20

type coverageData struct {
	// Corpus is the Forge commit the corpus was fetched at, "" when no lock
	// file is present.
	Corpus    string
	Cards     int
	Supported int
	Tokens    int
	ByType    []cards.CoverageGroup
	ByColour  []cards.CoverageGroup
	ByMana    []cards.CoverageGroup
	Missing   []cards.MissingPrimitive
}

func (d coverageData) percent() float64 {
	if d.Cards == 0 {
		return 0
	}
	return 100 * float64(d.Supported) / float64(d.Cards)
}

// byCountThenKey re-sorts a CoverageBy result into the order a reader wants
// for an unordered axis: biggest bucket first, ties broken on the key so the
// output stays deterministic.
func byCountThenKey(g []cards.CoverageGroup) []cards.CoverageGroup {
	out := append([]cards.CoverageGroup(nil), g...)
	sort.Slice(out, func(i, j int) bool {
		if out[i].Cards != out[j].Cards {
			return out[i].Cards > out[j].Cards
		}
		return out[i].Key < out[j].Key
	})
	return out
}

func measureCoverage(r *cards.Registry, dir string) coverageData {
	sup := effects.Supported()
	cv := r.Coverage(sup)
	d := coverageData{
		Cards:     cv.Cards,
		Supported: cv.Supported,
		Tokens:    len(r.Tokens),
		ByType:    byCountThenKey(r.CoverageBy(sup, cards.PrimaryTypeGroup)),
		ByColour:  byCountThenKey(r.CoverageBy(sup, cards.ColourGroup)),
		ByMana:    r.CoverageBy(sup, cards.ManaValueGroup),
		Missing:   cv.TopMissing(topMissingInDoc),
	}
	if l, err := cards.ReadLock(dir); err == nil {
		d.Corpus = l.Commit
	}
	return d
}

func groupTable(b *strings.Builder, header string, g []cards.CoverageGroup) {
	fmt.Fprintf(b, "| %s | Cards | Playable | %% |\n|---|---:|---:|---:|\n", header)
	for _, row := range g {
		fmt.Fprintf(b, "| %s | %d | %d | %.1f%% |\n", row.Key, row.Cards, row.Supported, row.Percent())
	}
}

// renderSummary is the block README.md carries between its markers: the
// headline number and the by-type split, and nothing else. The full breakdown
// stays in docs/coverage.md, which this block links to.
func renderSummary(d coverageData) string {
	var b strings.Builder
	b.WriteString(readmeBeginMarker)
	b.WriteString("\n<!-- generated by `make coverage`; edit the generator, not this block -->\n\n")
	fmt.Fprintf(&b, "Of the **%d** cards in the compiled Forge corpus, gorge can fully play **%d (%.1f%%)** —\n",
		d.Cards, d.Supported, d.percent())
	b.WriteString("every primitive the card's script names is implemented. By card type:\n\n")
	groupTable(&b, "Card type", d.ByType)
	b.WriteString("\nFull breakdown, including colour, mana value and what the remaining gap is\nwaiting on: [docs/coverage.md](docs/coverage.md).\n")
	b.WriteString(readmeEndMarker)
	return b.String()
}

func renderCoverageDoc(d coverageData) string {
	var b strings.Builder
	b.WriteString("# Card coverage\n\n")
	b.WriteString("<!-- generated by `make coverage`; edit cmd/forgec/coverage.go, not this file -->\n\n")
	fmt.Fprintf(&b, "gorge compiles [Card-Forge/forge](https://github.com/Card-Forge/forge)'s card\nscripts into an IR and implements the primitives that IR names. A card counts\nas **playable** here when every primitive its script references is implemented;\none missing primitive makes the whole card unplayable, so this is a strict\nlower bound on what the engine can do.\n\n")
	fmt.Fprintf(&b, "- Cards in the corpus: **%d**\n", d.Cards)
	fmt.Fprintf(&b, "- Fully playable: **%d (%.1f%%)**\n", d.Supported, d.percent())
	fmt.Fprintf(&b, "- Token scripts compiled: **%d**\n", d.Tokens)
	if d.Corpus != "" {
		fmt.Fprintf(&b, "- Corpus pin: `Card-Forge/forge@%s`\n", d.Corpus)
	}
	b.WriteString("\n## Why not by set?\n\n")
	b.WriteString("Forge card scripts carry no set or edition data: a script is one card's\nbehaviour, independent of which set printed it. Set membership lives in a\nseparate Forge resource tree that `forgec fetch` deliberately does not pull.\nSo the breakdown below groups by what the compiled IR does carry — card type,\ncolour and mana value. Card type is the informative axis: it tracks which\nengine subsystems are finished.\n\n")
	b.WriteString("## By card type\n\n")
	groupTable(&b, "Card type", d.ByType)
	b.WriteString("\n## By colour\n\n")
	b.WriteString("Colour here is the card's printed colour — the colours of its mana cost and\ncolour indicator — not its Commander colour identity.\n\n")
	groupTable(&b, "Colour", d.ByColour)
	b.WriteString("\n## By mana value\n\n")
	groupTable(&b, "Mana value", d.ByMana)
	b.WriteString("\n## What the gap is waiting on\n\n")
	b.WriteString("Each row is one unimplemented primitive and how many otherwise-playable cards\nit alone blocks. Implementing the top row unlocks that many cards at once.\n\n")
	b.WriteString("| Primitive | Cards blocked |\n|---|---:|\n")
	for _, m := range d.Missing {
		fmt.Fprintf(&b, "| `%s` | %d |\n", m.Name, m.Cards)
	}
	b.WriteString("\nRegenerate this file with `make coverage`.\n")
	return b.String()
}

// spliceSummary replaces the marked block in readme with section. A README
// missing either marker is an error, never a silent append: the whole point of
// the markers is that the refresh job edits exactly one region.
func spliceSummary(readme, section string) (string, error) {
	i := strings.Index(readme, readmeBeginMarker)
	j := strings.Index(readme, readmeEndMarker)
	if i < 0 || j < 0 || j < i {
		return "", fmt.Errorf("README is missing the %s / %s markers", readmeBeginMarker, readmeEndMarker)
	}
	return readme[:i] + section + readme[j+len(readmeEndMarker):], nil
}

// coverageCmd writes (or, with check, verifies) the coverage tables. In check
// mode it never writes: it reports which file is stale and how to fix it, and
// exits non-zero via the returned error.
func coverageCmd(dir, docPath, readmePath string, check bool) error {
	r, err := loadReportRegistry(dir)
	if err != nil {
		return err
	}
	d := measureCoverage(r, dir)
	// A corpus that compiled but yielded nothing is a broken fetch, not 0%
	// coverage. Refuse rather than publish a table of zeroes.
	if d.Cards == 0 {
		return fmt.Errorf("no named cards in %s — the corpus is missing or empty; run `make fetch-cards`", dir)
	}

	doc := renderCoverageDoc(d)
	readmeOld, err := os.ReadFile(readmePath)
	if err != nil {
		return err
	}
	readmeNew, err := spliceSummary(string(readmeOld), renderSummary(d))
	if err != nil {
		return fmt.Errorf("%s: %w", readmePath, err)
	}

	want := map[string]string{docPath: doc, readmePath: readmeNew}
	if check {
		var stale []string
		for _, p := range []string{docPath, readmePath} {
			cur, err := os.ReadFile(p)
			if err != nil || string(cur) != want[p] {
				stale = append(stale, p)
			}
		}
		if len(stale) > 0 {
			return fmt.Errorf("coverage tables are stale (%s) — run `make coverage` and commit the result",
				strings.Join(stale, ", "))
		}
		fmt.Printf("coverage: up to date (%d/%d, %.1f%%)\n", d.Supported, d.Cards, d.percent())
		return nil
	}

	changed := false
	for _, p := range []string{docPath, readmePath} {
		cur, err := os.ReadFile(p)
		if err == nil && string(cur) == want[p] {
			continue
		}
		if err := os.WriteFile(p, []byte(want[p]), 0o644); err != nil {
			return err
		}
		changed = true
		fmt.Printf("coverage: wrote %s\n", p)
	}
	if !changed {
		fmt.Println("coverage: already up to date")
	}
	fmt.Printf("coverage: %d/%d cards playable (%.1f%%)\n", d.Supported, d.Cards, d.percent())
	return nil
}
