package effects

import "github.com/adams-shaun/gorge/cards"

// modelledValueHeads is every count-expression head (cards.ValueHead) the
// evaluator in this package models: a Count$<Head> or PlayerCount<Group>$
// <Property> body whose head is listed here resolves (EvalCountOK's ok),
// one whose head is absent falls through to the unresolved verdict. The
// list feeds Supported as "count:<head>" primitives, so cards.Registry.
// Unsupported reports a card reading an unlisted head -- a gate that could
// never be evaluated, an amount that read a meaningless zero -- as
// unsupported instead of counting it playable (fuzz-cov3, the cardfuzz
// coverage audit's registration-honesty gap).
//
// It is not hand-trusted: rules' TestValueHeadRegistryMatchesEvaluator
// evaluates every referenced value body in the corpus against a real
// engine and fails, in both directions, when a listed head never resolves
// or an unlisted head does. Adding an evaluator arm therefore means adding
// its head here, and the test names it. Sorted.
var modelledValueHeads = []string{
	"AttackersDeclared",
	"Blessing",
	"CardCounters",
	"CardManaCost",
	"CardNumAttacksThisTurn",
	"CardNumColors",
	"CardPower",
	"CardToughness",
	"CardsInYourHand",
	"CastTotalManaSpent",
	"ChosenNumber",
	"ChosenSize",
	"ColorsColorIdentity",
	"Compare",
	"Converge",
	"CountersAddedThisTurn",
	"CreaturesAttackedThisTurn",
	"Delirium",
	"Devotion",
	"DevotionDual",
	"DifferentCounterKinds",
	"Domain",
	"DomainActivePlayer",
	"FatefulHour",
	"Foretold",
	"Hellbent",
	"IfCastInOwnMainPhase",
	"InOwnMainPhase",
	"Kicked",
	"Landfall",
	"LeftBattlefieldThisTurn",
	"LeftGraveyardThisTurn",
	"LifeOppsLostThisTurn",
	"LifeYouGainedThisTurn",
	"LifeYouLostThisTurn",
	"MaxOppDamageThisTurn",
	"Metalcraft",
	"Monarch",
	"Morbid",
	"MostCardName",
	"NotedNumber",
	"OppGreatestLifeTotal",
	"OptionalGenericCostPaid",
	"Party",
	"PlayerCount$SacrificedThisTurn",
	"PlayerCountDefinedRegistered$HasPropertywasDealtCombatDamageThisTurnBy",
	"PlayerCountDefinedRegistered$HighestLifeLostThisTurn",
	"PlayerCountDefinedRegistered.Other$HasPropertyLostLifeThisTurn",
	"PlayerCountHasLost$Amount",
	"PlayerCountOpponents$Amount",
	"PlayerCountOpponents$ConditionGE2",
	"PlayerCountOpponents$ConditionGE3",
	"PlayerCountOpponents$ConditionLTZ",
	"PlayerCountOpponents$HasPropertyHasCardsInHand",
	"PlayerCountOpponents$HasPropertyIsCorrupted",
	"PlayerCountOpponents$HasPropertyLostLifeThisTurn",
	"PlayerCountOpponents$HasPropertywasDealtCombatDamageThisTurn",
	"PlayerCountOpponents$HasPropertywasDealtDamageThisTurn",
	"PlayerCountOpponents$HighestCardsDrawn",
	"PlayerCountOpponents$HighestCardsInGraveyard",
	"PlayerCountOpponents$HighestCardsInHand",
	"PlayerCountOpponents$HighestCounters",
	"PlayerCountOpponents$HighestLifeTotal",
	"PlayerCountOpponents$HighestValid",
	"PlayerCountOpponents$HighestValidGraveyard",
	"PlayerCountOpponents$LifeLostLastTurn",
	"PlayerCountOpponents$LowestCardsInHand",
	"PlayerCountOpponents$LowestLifeTotal",
	"PlayerCountOpponents$LowestValid",
	"PlayerCountPlayers$Amount",
	"PlayerCountPlayers$AttackersDeclared",
	"PlayerCountPlayers$ConditionGE1",
	"PlayerCountPlayers$ConditionLEY",
	"PlayerCountPlayers$Counters",
	"PlayerCountPlayers$HasPropertyHasCardsInGraveyard",
	"PlayerCountPlayers$HasPropertyLostLifeThisTurn",
	"PlayerCountPlayers$HasPropertyattackedYouTheirLastTurn",
	"PlayerCountPlayers$HasPropertyisMonarch",
	"PlayerCountPlayers$HasPropertywasDealtCombatDamageThisTurn",
	"PlayerCountPlayers$HighestCardsInGraveyard",
	"PlayerCountPlayers$HighestCardsInHand",
	"PlayerCountPlayers$HighestLifeTotal",
	"PlayerCountPlayers$HighestValid",
	"PlayerCountPlayers$HighestValidGraveyard",
	"PlayerCountPlayers$LowestLifeTotal",
	"PlayerCountPlayers$LowestValid",
	"PlayerCountPlayers$LowestValidHand",
	"PlayerCountPlayers$LowestValidLibrary",
	"PlayerCountPlayers$SacrificedThisTurn",
	"PlayerCountPropertyYou$CardsDiscardedThisTurn",
	"PlayerCountPropertyYou$DomainPlayer",
	"PlayerCountPropertyYou$HasPropertyActive",
	"PlayerCountPropertyYou$HasPropertyBeenAttackedThisCombat",
	"PlayerCountPropertyYou$LandsPlayed",
	"PlayerCountPropertyYou$LifeLostLastTurn",
	"PlayerCountPropertyYou$LifeLostThisTurn",
	"PlayerCountPropertyYou$OpponentsAttackedThisCombat",
	"PlayerCountPropertyYou$RingTemptedYou",
	"PlayerCountPropertyYou$SacrificedThisTurn",
	"PlayerCountRegisteredOpponents$HasPropertywasDealtCombatDamageThisTurn",
	"PlayerCountRegisteredOpponents$HasPropertywasDealtCombatDamageThisTurnBy",
	"PlayerCountRegisteredOpponents$HasPropertywasDealtDamageThisTurn",
	"PlayerCountRegisteredOpponents$HighestLifeLostThisTurn",
	"PlayerCountRemembered$Amount",
	"PlayerCountRemembered$CardsDrawn",
	"PlayerCountRemembered$CardsInHand",
	"PlayerCountRemembered$CardsInLibrary",
	"PlayerCountRemembered$LifeLostThisTurn",
	"PlayerCountRemembered$LifeTotal",
	"PlayerCountRememberedController$Amount",
	"PlayerCountRememberedController$CardsInHand",
	"PlayerCountRememberedController$CardsInLibrary",
	"PlayerCountRememberedController$HasPropertyOpponent",
	"PromisedGift",
	"RememberedNumber",
	"RememberedSize",
	"ResolvedThisTurn",
	"Revolt",
	"StartingPlayer",
	"ThisTurnCast",
	"ThisTurnEntered",
	"Threshold",
	"TimesKicked",
	"TimesMutated",
	"TopOfLibraryCMC",
	"TotalCommanderCastFromCommandZone",
	"TotalOppPoisonCounters",
	"TotalTurns",
	"UrzaLands",
	"Valid",
	"ValidAll",
	"ValidBattlefield,Command",
	"ValidBattlefield,Graveyard",
	"ValidBattlefield,Hand",
	"ValidCommand",
	"ValidExile",
	"ValidExile,Graveyard",
	"ValidGraveyard",
	"ValidGraveyard,Battlefield",
	"ValidGraveyard,Exile",
	"ValidGraveyard,Hand,Library",
	"ValidGraveyard,Library,Hand",
	"ValidHand",
	"ValidHand,Graveyard",
	"ValidLibrary",
	"ValidStack",
	"Void",
	"YouDescendedThisTurn",
	"YouDrewThisTurn",
	"YourCountersEnergy",
	"YourCountersExperience",
	"YourCountersRAD",
	"YourLifeTotal",
	"YourStartingLife",
	"YourTurns",
	"wasCastFromExile",
	"wasCastFromGraveyard",
	"wasCastFromYourHand",
	"wasCastFromYourHandByYou",
	"xPaid",
}

// ModelledValueHeads returns a copy of the modelled count-head list.
func ModelledValueHeads() []string {
	return append([]string(nil), modelledValueHeads...)
}

func init() {
	prefixed := make([]string, len(modelledValueHeads))
	for i, h := range modelledValueHeads {
		prefixed[i] = cards.ValueHeadPrefix + h
	}
	RegisterNonAPI(prefixed...)
}
