// Package tsgen turns Go structs into TypeScript interfaces by reflection:
// json tags name the fields, omitempty makes them optional, pointers admit
// null, slices become arrays, string-keyed maps become Records. It exists
// so web/src/protocol.ts can never drift from package protocol — the
// committed file is regenerated by cmd/gentypes and diff-checked in lint.
package tsgen

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"
)

// Options drives one generation. Roots are walked transitively; Unions are
// emitted as string-literal union types (name -> values), sorted by name.
type Options struct {
	Roots  []reflect.Type
	Unions map[string][]string
	Header string
}

var rawMessage = reflect.TypeOf(json.RawMessage{})

type gen struct {
	order []reflect.Type
	seen  map[reflect.Type]bool
	names map[string]reflect.Type
	err   error
}

// Generate renders the header, the unions, then one interface per struct in
// first-encounter order (roots first, nested types as they are met). Two
// distinct struct types with the same Name() are an error, as is an
// anonymous struct: the output needs a stable, unique name for each.
func Generate(o Options) (string, error) {
	g := &gen{seen: map[reflect.Type]bool{}, names: map[string]reflect.Type{}}
	for _, r := range o.Roots {
		g.visit(r)
		if g.err != nil {
			return "", g.err
		}
	}
	var b strings.Builder
	b.WriteString(o.Header)
	b.WriteString("// Code generated by cmd/gentypes; DO NOT EDIT.\n")
	unionNames := make([]string, 0, len(o.Unions))
	for n := range o.Unions {
		unionNames = append(unionNames, n)
	}
	sort.Strings(unionNames)
	for _, n := range unionNames {
		vals := make([]string, len(o.Unions[n]))
		for i, v := range o.Unions[n] {
			vals[i] = fmt.Sprintf("%q", v)
		}
		fmt.Fprintf(&b, "\nexport type %s = %s;\n", n, strings.Join(vals, " | "))
	}
	for _, t := range g.order {
		b.WriteString("\n")
		g.writeStruct(&b, t)
	}
	return b.String(), nil
}

// visit registers t (a struct) and every struct reachable from its fields.
func (g *gen) visit(t reflect.Type) {
	t = deref(t)
	if t.Kind() != reflect.Struct || t == rawMessage || g.seen[t] || g.err != nil {
		return
	}
	if t.Name() == "" {
		g.err = fmt.Errorf("tsgen: anonymous struct in %v cannot be named", t)
		return
	}
	if prev, ok := g.names[t.Name()]; ok && prev != t {
		g.err = fmt.Errorf("tsgen: two structs named %s: %v and %v", t.Name(), prev, t)
		return
	}
	g.seen[t] = true
	g.names[t.Name()] = t
	// Fields are visited before t is appended so nested types are declared
	// first; TypeScript does not need that, but a reader does.
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if name, _ := jsonName(f); name == "" {
			continue
		}
		g.visit(elemStruct(f.Type))
	}
	g.order = append(g.order, t)
}

func (g *gen) writeStruct(b *strings.Builder, t reflect.Type) {
	fmt.Fprintf(b, "export interface %s {\n", t.Name())
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		name, omitempty := jsonName(f)
		if name == "" {
			continue
		}
		q := ""
		if omitempty {
			q = "?"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", name, q, tsType(f.Type))
	}
	b.WriteString("}\n")
}

// jsonName is the wire name and whether omitempty is set; "" means skip
// (json:"-" or an unexported field).
func jsonName(f reflect.StructField) (string, bool) {
	if f.PkgPath != "" {
		return "", false
	}
	tag := f.Tag.Get("json")
	if tag == "-" {
		return "", false
	}
	name, opts, _ := strings.Cut(tag, ",")
	if name == "" {
		name = f.Name
	}
	return name, strings.Contains(opts, "omitempty")
}

// tsType maps one Go type to TypeScript.
func tsType(t reflect.Type) string {
	switch {
	case t == rawMessage:
		return "unknown"
	case t.Kind() == reflect.Pointer:
		return tsType(t.Elem()) + " | null"
	case t.Kind() == reflect.Interface:
		return "unknown"
	case t.Kind() == reflect.Bool:
		return "boolean"
	case t.Kind() == reflect.String:
		return "string"
	case t.Kind() >= reflect.Int && t.Kind() <= reflect.Float64:
		return "number"
	case t.Kind() == reflect.Slice && t.Elem().Kind() == reflect.Uint8:
		return "string" // encoding/json base64-encodes []byte
	case t.Kind() == reflect.Slice:
		return tsType(t.Elem()) + "[]"
	case t.Kind() == reflect.Array:
		parts := make([]string, t.Len())
		for i := range parts {
			parts[i] = tsType(t.Elem())
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case t.Kind() == reflect.Map:
		return "Record<string, " + tsType(t.Elem()) + ">"
	case t.Kind() == reflect.Struct:
		return t.Name()
	}
	return "unknown"
}

func deref(t reflect.Type) reflect.Type {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	return t
}

// elemStruct digs through pointers, slices, arrays and maps to the struct a
// field ultimately holds, if any.
func elemStruct(t reflect.Type) reflect.Type {
	for {
		switch t.Kind() {
		case reflect.Pointer, reflect.Slice, reflect.Array, reflect.Map:
			t = t.Elem()
		default:
			return t
		}
	}
}
