package main

import (
	"bytes"
	"encoding/json"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/adams-shaun/gorge/internal/testutil/feedback"
	"github.com/adams-shaun/gorge/replay"
)

// fixtureRel is the committed fixture's path from this package's directory
// (the test binary's cwd): a real snapshot produced by the feedback
// capture's own code, regenerated by TestGenerateCommittedFixture when the
// corpus pin moves.
const fixtureRel = "testdata/feedback/" + fixtureID

// requireCorpus skips when the worktree has no .cards/ corpus: every
// repro test replays a match, and a corpus-backed replay is impossible
// without it. Skipping (not failing) matches testutil.CorpusRegistry's
// clean-clone convention — but note a skipped run here exercises nothing,
// so a green result without a corpus proves nothing.
func requireCorpus(t *testing.T) {
	t.Helper()
	root, err := feedback.Root()
	if err != nil {
		t.Skipf("no repo root: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, ".cards")); err != nil {
		t.Skip("no .cards/ corpus present — run `make fetch-cards compile-cards`")
	}
}

// TestReproFixtureSummaryExitsZero is the committed fixture's gate: the
// CLI on it verifies the head and prints the summary, exiting 0.
func TestReproFixtureSummaryExitsZero(t *testing.T) {
	requireCorpus(t)
	var out bytes.Buffer
	if code := run([]string{fixtureRel}, &out, io.Discard); code != 0 {
		t.Fatalf("exit %d, output:\n%s", code, out.String())
	}
	for _, want := range []string{
		"== feedback report " + fixtureID,
		"replayed 21 of 21 recorded intents", // the fixture's own counts; regenerate both together
		"recorded head",
		"turn 2, round 1",
		"active: seat 1, priority: seat 0",
		"life 20",
		"Underground Sea",
		"stack (top last):", // absent on an empty stack? checked loosely below
		"last log lines:",
	} {
		if want == "stack (top last):" {
			continue // the stack is empty at this point of the fixture
		}
		if !strings.Contains(out.String(), want) {
			t.Errorf("summary output missing %q:\n%s", want, out.String())
		}
	}
	// The empty stack prints nothing; the battlefield, the pending decision
	// and the log tail are what must be there.
	for _, want := range []string{"pending:", "Player 1", "Player 2"} {
		if !strings.Contains(out.String(), want) {
			t.Errorf("summary output missing %q", want)
		}
	}
}

// TestReproFixtureTamperedHeadExitsNonzero: a snapshot whose log.json head
// field does not match its own event chain is refused before the engine
// even runs, with DIVERGED and a non-zero exit.
func TestReproFixtureTamperedHeadExitsNonzero(t *testing.T) {
	requireCorpus(t)
	dir := tamperFixture(t, func(lg map[string]any) {
		lg["head"] = "deadbeefdeadbeef"
	})
	var out bytes.Buffer
	if code := run([]string{dir}, &out, io.Discard); code == 0 {
		t.Fatalf("tampered head exited 0:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "DIVERGED") {
		t.Errorf("output missing DIVERGED:\n%s", out.String())
	}
}

// TestReproFixtureTamperedEventNamesFirstSeq: a snapshot whose recorded
// events no longer replay (here: one draw's object id altered) diverges
// at the first mismatching event, and the output names that seq and says a
// corpus change is an expected cause.
func TestReproFixtureTamperedEventNamesFirstSeq(t *testing.T) {
	requireCorpus(t)
	dir := tamperFixture(t, func(lg map[string]any) {
		evs := lg["events"].([]any)
		// Kind is a JSON number (Kind carries no text encoding on the wire);
		// kindNames orders game_start 0, shuffle 1, move_zone 2, draw 3, so
		// the first draw is the first event whose kind is 3.
		for _, ev := range evs {
			e := ev.(map[string]any)
			if e["kind"] == float64(3) { // draw
				e["obj"] = float64(e["obj"].(float64) + 1000)
				return
			}
		}
		panic("fixture carries no draw event to tamper")
	})
	var out bytes.Buffer
	if code := run([]string{dir}, &out, io.Discard); code == 0 {
		t.Fatalf("tampered event exited 0:\n%s", out.String())
	}
	got := out.String()
	if !strings.Contains(got, "DIVERGED") {
		t.Errorf("output missing DIVERGED:\n%s", got)
	}
	if !strings.Contains(got, "corpus change") {
		t.Errorf("output missing the expected-cause note:\n%s", got)
	}
	// The divergence is named at the tampered event, not at the end.
	if !strings.Contains(got, "diverged at event") {
		t.Errorf("output missing the diverging seq:\n%s", got)
	}
}

// TestReproFixtureListPrintsTimeline: -list prints one line per recorded
// intent with its index, seat and decision, and exits 0.
func TestReproFixtureListPrintsTimeline(t *testing.T) {
	requireCorpus(t)
	var out bytes.Buffer
	if code := run([]string{"-list", fixtureRel}, &out, io.Discard); code != 0 {
		t.Fatalf("exit %d, output:\n%s", code, out.String())
	}
	lines := strings.Split(strings.TrimSpace(out.String()), "\n")
	if len(lines) != 21+1 { // one per intent, plus the game-not-over silence
		t.Logf("timeline:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "  0  seat 0  priority") {
		t.Errorf("timeline missing intent 0:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "Play Underground Sea") {
		t.Errorf("timeline missing a choice summary:\n%s", out.String())
	}
}

// TestReproFixtureAtReplaysToIntent: -at N replays to intent N instead of
// the capture point, and the summary reflects the earlier moment.
func TestReproFixtureAtReplaysToIntent(t *testing.T) {
	requireCorpus(t)
	var out bytes.Buffer
	if code := run([]string{"-at", "6", fixtureRel}, &out, io.Discard); code != 0 {
		t.Fatalf("exit %d, output:\n%s", code, out.String())
	}
	for _, want := range []string{"replayed 6 of 21 recorded intents", "turn 1, round 1, main1", "pending: seat 0 choose"} {
		if !strings.Contains(out.String(), want) {
			t.Errorf("summary missing %q:\n%s", want, out.String())
		}
	}
}

// TestReproFixtureOmniscientShowsHands: -omniscient prints every seat's
// hand; the default summary prints sizes only.
func TestReproFixtureOmniscientShowsHands(t *testing.T) {
	requireCorpus(t)
	var pub, omni bytes.Buffer
	if code := run([]string{fixtureRel}, &pub, io.Discard); code != 0 {
		t.Fatalf("public exit %d", code)
	}
	if code := run([]string{"-omniscient", fixtureRel}, &omni, io.Discard); code != 0 {
		t.Fatalf("omniscient exit %d", code)
	}
	if strings.Contains(pub.String(), "  hand: ") {
		t.Errorf("public summary leaked a hand:\n%s", pub.String())
	}
	if !strings.Contains(omni.String(), "  hand: ") {
		t.Errorf("omniscient summary missing hands:\n%s", omni.String())
	}
}

// TestEngineAtMatchesReplayToHeads pins the brief's equality gate: for a
// spread of intent counts, EngineAt's engine and a hand-rolled
// replay.ReplayTo over the same snapshot's (Log, Config) stand at the same
// head — the same replay by construction, not two code paths.
func TestEngineAtMatchesReplayToHeads(t *testing.T) {
	requireCorpus(t)
	l, cfg, meta, err := feedback.Load(fixtureRel)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	for _, n := range []int{-1, 0, 1, 7, meta.IntentCount - 1, meta.IntentCount} {
		e1 := feedback.EngineAt(t, fixtureRel, n)
		e2, err := replay.ReplayTo(l, cfg, n)
		if err != nil {
			t.Fatalf("ReplayTo(%d): %v", n, err)
		}
		if e1.L.Head() != e2.L.Head() || len(e1.L.Events) != len(e2.L.Events) {
			t.Errorf("n=%d: EngineAt head %s (%d events), ReplayTo head %s (%d events)",
				n, e1.L.Head(), len(e1.L.Events), e2.L.Head(), len(e2.L.Events))
		}
	}
}

// TestReproOnFreshSnapshot runs the whole product on a snapshot captured
// live by the feedback capture's own code in this test — not the committed
// fixture — so the loader cannot drift from the capture shape without this
// failing. The corpus pin coupling the committed fixture carries does not
// apply here: the capture and the replay run against the same corpus.
func TestReproOnFreshSnapshot(t *testing.T) {
	requireCorpus(t)
	advance, r := gatedFixtureRegistry(t)
	advance(12)
	dir := t.TempDir()
	captureSnapshotFiles(t, r, dir)

	var out bytes.Buffer
	if code := run([]string{dir}, &out, io.Discard); code != 0 {
		t.Fatalf("exit %d, output:\n%s", code, out.String())
	}
	if !strings.Contains(out.String(), "replayed 21 of 21 recorded intents") {
		t.Errorf("fresh snapshot summary unexpected:\n%s", out.String())
	}
	out.Reset()
	if code := run([]string{"-list", dir}, &out, io.Discard); code != 0 {
		t.Fatalf("list exit %d, output:\n%s", code, out.String())
	}
}

// TestReproEmitTestSkeletonCompilesAndFailsOnTODO: -emit-test copies the
// snapshot into the target package's testdata and writes a test that
// compiles and fails only on its TODO. The target is a scratch package
// under the repo root (a real package the go tool builds), removed on
// cleanup.
func TestReproEmitTestSkeletonCompilesAndFailsOnTODO(t *testing.T) {
	requireCorpus(t)
	root, err := feedback.Root()
	if err != nil {
		t.Skipf("no repo root: %v", err)
	}
	scratch := filepath.Join(root, "zzrepro-emittest")
	t.Cleanup(func() { os.RemoveAll(scratch) })
	if err := os.MkdirAll(scratch, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(scratch, "doc.go"), []byte("package emittmp\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	var out bytes.Buffer
	if code := run([]string{"-emit-test", "zzrepro-emittest", fixtureRel}, &out, io.Discard); code != 0 {
		t.Fatalf("emit exit %d, output:\n%s", code, out.String())
	}
	if _, err := os.Stat(filepath.Join(scratch, "testdata", "feedback", fixtureID, "match.json")); err != nil {
		t.Errorf("snapshot not copied: %v", err)
	}

	// The generated test compiles and fails on its TODO, not on load.
	cmd := exec.Command("go", "test", "./zzrepro-emittest", "-run", "TestFeedbackRepro20260914T120000Z_fb01")
	cmd.Dir = root
	raw, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("generated test passed; it must fail on the TODO:\n%s", raw)
	}
	if !strings.Contains(string(raw), "TODO: assert the reported behaviour") {
		t.Fatalf("generated test failed for another reason:\n%s", raw)
	}
}

// TestReproEmitTestRefusesOverwrite: a second emit at the same target is
// refused rather than clobbering a test someone may have filled in.
func TestReproEmitTestRefusesOverwrite(t *testing.T) {
	requireCorpus(t)
	root, err := feedback.Root()
	if err != nil {
		t.Skipf("no repo root: %v", err)
	}
	scratch := filepath.Join(root, "zzrepro-emittest2")
	t.Cleanup(func() { os.RemoveAll(scratch) })
	if err := os.MkdirAll(scratch, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(scratch, "doc.go"), []byte("package emittmp\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	if code := run([]string{"-emit-test", "zzrepro-emittest2", fixtureRel}, &out, io.Discard); code != 0 {
		t.Fatalf("first emit exit %d:\n%s", code, out.String())
	}
	out.Reset()
	if code := run([]string{"-emit-test", "zzrepro-emittest2", fixtureRel}, &out, io.Discard); code == 0 {
		t.Fatalf("second emit overwrote the first:\n%s", out.String())
	}
}

// tamperFixture copies the committed fixture into a temp dir and rewrites
// its log.json through edit.
func tamperFixture(t *testing.T, edit func(map[string]any)) string {
	t.Helper()
	dir := t.TempDir()
	for _, f := range []string{"match.json", "view.json", "report.json"} {
		raw, err := os.ReadFile(filepath.Join(fixtureRel, f))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, f), raw, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	raw, err := os.ReadFile(filepath.Join(fixtureRel, "log.json"))
	if err != nil {
		t.Fatal(err)
	}
	var lg map[string]any
	if err := json.Unmarshal(raw, &lg); err != nil {
		t.Fatal(err)
	}
	edit(lg)
	out, err := json.Marshal(lg)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "log.json"), out, 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}
