package main

import (
	"bytes"
	"encoding/json"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/adams-shaun/gorge/internal/testutil/feedback"
	"github.com/adams-shaun/gorge/replay"
	"github.com/adams-shaun/gorge/view"
)

// fixtureRel is the committed fixture's path from this package's directory
// (the test binary's cwd): a real snapshot produced by the feedback
// capture's own code, regenerated by TestGenerateCommittedFixture when the
// corpus pin moves.
const fixtureRel = "testdata/feedback/" + fixtureID

// requireCorpus skips when the worktree has no .cards/ corpus: every
// repro test replays a match, and a corpus-backed replay is impossible
// without it. Skipping (not failing) matches testutil.CorpusRegistry's
// clean-clone convention — but note a skipped run here exercises nothing,
// so a green result without a corpus proves nothing.
func requireCorpus(t *testing.T) {
	t.Helper()
	root, err := feedback.Root()
	if err != nil {
		t.Skipf("no repo root: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, ".cards")); err != nil {
		t.Skip("no .cards/ corpus present — run `make fetch-cards compile-cards`")
	}
}

// TestReproFixtureSummaryExitsZero is the committed fixture's gate: the
// CLI on it verifies the head and prints the summary, exiting 0.
func TestReproFixtureSummaryExitsZero(t *testing.T) {
	requireCorpus(t)
	var out bytes.Buffer
	if code := run([]string{fixtureRel}, &out, io.Discard); code != 0 {
		t.Fatalf("exit %d, output:\n%s", code, out.String())
	}
	for _, want := range []string{
		"== feedback report " + fixtureID,
		"replayed 21 of 21 recorded intents", // the fixture's own counts; regenerate both together
		"recorded head",
		"turn 2, round 1",
		"active: seat 1, priority: seat 0",
		"life 20",
		"Underground Sea",
		"stack (top last):", // absent on an empty stack? checked loosely below
		"last log lines:",
	} {
		if want == "stack (top last):" {
			continue // the stack is empty at this point of the fixture
		}
		if !strings.Contains(out.String(), want) {
			t.Errorf("summary output missing %q:\n%s", want, out.String())
		}
	}
	// The empty stack prints nothing; the battlefield, the pending decision
	// and the log tail are what must be there.
	for _, want := range []string{"pending:", "Player 1", "Player 2"} {
		if !strings.Contains(out.String(), want) {
			t.Errorf("summary output missing %q", want)
		}
	}
}

// TestReproFixtureTamperedHeadExitsNonzero: a snapshot whose log.json head
// field does not match its own event chain is refused before the engine
// even runs, with DIVERGED and a non-zero exit.
func TestReproFixtureTamperedHeadExitsNonzero(t *testing.T) {
	requireCorpus(t)
	dir := tamperFixture(t, func(lg map[string]any) {
		lg["head"] = "deadbeefdeadbeef"
	})
	var out bytes.Buffer
	if code := run([]string{dir}, &out, io.Discard); code == 0 {
		t.Fatalf("tampered head exited 0:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "DIVERGED") {
		t.Errorf("output missing DIVERGED:\n%s", out.String())
	}
}

// TestReproFixtureTamperedEventNamesFirstSeq: a snapshot whose recorded
// events no longer replay (here: one draw's object id altered) diverges
// at the first mismatching event, and the output names that seq and says a
// corpus change is an expected cause.
func TestReproFixtureTamperedEventNamesFirstSeq(t *testing.T) {
	requireCorpus(t)
	dir := tamperFixture(t, func(lg map[string]any) {
		evs := lg["events"].([]any)
		// Kind is a JSON number (Kind carries no text encoding on the wire);
		// kindNames orders game_start 0, shuffle 1, move_zone 2, draw 3, so
		// the first draw is the first event whose kind is 3.
		for _, ev := range evs {
			e := ev.(map[string]any)
			if e["kind"] == json.Number("3") { // draw
				obj, err := e["obj"].(json.Number).Int64()
				if err != nil {
					panic(err)
				}
				e["obj"] = obj + 1000
				return
			}
		}
		panic("fixture carries no draw event to tamper")
	})
	var out bytes.Buffer
	if code := run([]string{dir}, &out, io.Discard); code == 0 {
		t.Fatalf("tampered event exited 0:\n%s", out.String())
	}
	got := out.String()
	if !strings.Contains(got, "DIVERGED") {
		t.Errorf("output missing DIVERGED:\n%s", got)
	}
	if !strings.Contains(got, "corpus change") {
		t.Errorf("output missing the expected-cause note:\n%s", got)
	}
	// The divergence is named at the tampered event, not at the end.
	if !strings.Contains(got, "diverged at event") {
		t.Errorf("output missing the diverging seq:\n%s", got)
	}
}

// TestReproFixtureListRejectsPostGenesisTamper pins -list to the same full
// validation boundary as an ordinary replay. Event 50 is the land-choice
// decision_made event, well after genesis; changing only its recorded answer
// used to leave the rendered timeline looking valid and exit 0.
func TestReproFixtureListRejectsPostGenesisTamper(t *testing.T) {
	requireCorpus(t)
	dir := tamperFixture(t, func(lg map[string]any) {
		e := lg["events"].([]any)[50].(map[string]any)
		e["text"] = "choose:[999]"
	})
	var out bytes.Buffer
	if code := run([]string{"-list", dir}, &out, io.Discard); code == 0 {
		t.Fatalf("-list accepted a tampered post-genesis event:\n%s", out.String())
	}
	for _, want := range []string{"DIVERGED", "diverged at event 50"} {
		if !strings.Contains(out.String(), want) {
			t.Errorf("output missing %q:\n%s", want, out.String())
		}
	}
}

// TestReproFixtureListPrintsTimeline: -list prints one line per recorded
// intent with its index, seat and decision, and exits 0.
func TestReproFixtureListPrintsTimeline(t *testing.T) {
	requireCorpus(t)
	var out bytes.Buffer
	if code := run([]string{"-list", fixtureRel}, &out, io.Discard); code != 0 {
		t.Fatalf("exit %d, output:\n%s", code, out.String())
	}
	lines := strings.Split(strings.TrimSpace(out.String()), "\n")
	if len(lines) != 21 { // one line per intent; this fixture is not game over
		t.Fatalf("timeline has %d lines, want 21:\n%s", len(lines), out.String())
	}
	if !strings.Contains(out.String(), "  0  seat 0  priority") {
		t.Errorf("timeline missing intent 0:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "Play Underground Sea") {
		t.Errorf("timeline missing a choice summary:\n%s", out.String())
	}
}

// TestReproFixtureAtReplaysToIntent: -at N replays to intent N instead of
// the capture point, and the summary reflects the earlier moment.
func TestReproFixtureAtReplaysToIntent(t *testing.T) {
	requireCorpus(t)
	var out bytes.Buffer
	if code := run([]string{"-at", "6", fixtureRel}, &out, io.Discard); code != 0 {
		t.Fatalf("exit %d, output:\n%s", code, out.String())
	}
	for _, want := range []string{"replayed 6 of 21 recorded intents", "turn 1, round 1, main1", "pending: seat 0 choose"} {
		if !strings.Contains(out.String(), want) {
			t.Errorf("summary missing %q:\n%s", want, out.String())
		}
	}
}

// TestReproFixtureAtRejectsTamperedCapture pins -at to the complete-capture
// validation boundary. A valid prefix is not enough: a forged final head may
// not be rendered as a verified reproduction.
func TestReproFixtureAtRejectsTamperedCapture(t *testing.T) {
	requireCorpus(t)
	dir := tamperFixture(t, func(lg map[string]any) {
		lg["head"] = "deadbeefdeadbeef"
	})
	var out bytes.Buffer
	if code := run([]string{"-at", "0", dir}, &out, io.Discard); code == 0 {
		t.Fatalf("-at accepted a corrupt full capture:\n%s", out.String())
	}
	for _, want := range []string{"DIVERGED", "log.json head"} {
		if !strings.Contains(out.String(), want) {
			t.Errorf("output missing %q:\n%s", want, out.String())
		}
	}
}

// TestReproFixtureAtRejectsOutOfRange refuses a requested point rather than
// relying on ReplayTo's library-level clamping and then labelling the clamped
// capture with the unchecked request.
func TestReproFixtureAtRejectsOutOfRange(t *testing.T) {
	requireCorpus(t)
	var stderr bytes.Buffer
	if code := run([]string{"-at", "999", fixtureRel}, io.Discard, &stderr); code != 2 {
		t.Fatalf("exit %d, want usage exit 2; stderr:\n%s", code, stderr.String())
	}
	if !strings.Contains(stderr.String(), "between 0 and 21 (got 999)") {
		t.Errorf("range error missing actual bounds:\n%s", stderr.String())
	}
}

// TestReproFixtureIgnoresTamperedIntentCount derives both the default replay
// point and its summary denominator from the actual intents array. The
// redundant intent_count capture metadata is not allowed to relabel state.
func TestReproFixtureIgnoresTamperedIntentCount(t *testing.T) {
	requireCorpus(t)
	dir := tamperFixture(t, func(lg map[string]any) {
		lg["intent_count"] = json.Number("999")
	})
	var out bytes.Buffer
	if code := run([]string{dir}, &out, io.Discard); code != 0 {
		t.Fatalf("exit %d, output:\n%s", code, out.String())
	}
	if !strings.Contains(out.String(), "replayed 21 of 21 recorded intents") {
		t.Errorf("summary trusted tampered intent_count:\n%s", out.String())
	}
}

// TestReproFixtureOmniscientShowsHands: -omniscient prints every seat's
// hand; the default summary prints sizes only.
func TestReproFixtureOmniscientShowsHands(t *testing.T) {
	requireCorpus(t)
	var pub, omni bytes.Buffer
	if code := run([]string{fixtureRel}, &pub, io.Discard); code != 0 {
		t.Fatalf("public exit %d", code)
	}
	if code := run([]string{"-omniscient", fixtureRel}, &omni, io.Discard); code != 0 {
		t.Fatalf("omniscient exit %d", code)
	}
	if strings.Contains(pub.String(), "  hand: ") {
		t.Errorf("public summary leaked a hand:\n%s", pub.String())
	}
	if !strings.Contains(omni.String(), "  hand: ") {
		t.Errorf("omniscient summary missing hands:\n%s", omni.String())
	}
}

// TestEngineAtMatchesReplayToHeads pins the brief's equality gate: for a
// spread of intent counts, EngineAt's engine and a hand-rolled
// replay.ReplayTo over the same snapshot's (Log, Config) stand at the same
// head — the same replay by construction, not two code paths. The negative
// case is NOT tautological: EngineAt normalizes n<0 to len(Intents) itself
// (ReplayTo clamps negatives to genesis), so EngineAt(-1) is compared
// against the explicit full-intent ReplayTo — and asserted to actually be
// the capture point, not genesis.
func TestEngineAtMatchesReplayToHeads(t *testing.T) {
	requireCorpus(t)
	l, cfg, meta, err := feedback.Load(fixtureRel)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	full, err := replay.Replay(l, cfg)
	if err != nil {
		t.Fatalf("full replay: %v", err)
	}
	for _, n := range []int{0, 1, 7, meta.IntentCount - 1, meta.IntentCount} {
		e1 := feedback.EngineAt(t, fixtureRel, n)
		e2, err := replay.ReplayTo(l, cfg, n)
		if err != nil {
			t.Fatalf("ReplayTo(%d): %v", n, err)
		}
		if e1.L.Head() != e2.L.Head() || len(e1.L.Events) != len(e2.L.Events) {
			t.Errorf("n=%d: EngineAt head %s (%d events), ReplayTo head %s (%d events)",
				n, e1.L.Head(), len(e1.L.Events), e2.L.Head(), len(e2.L.Events))
		}
	}
	neg := feedback.EngineAt(t, fixtureRel, -1)
	if neg.L.Head() != full.L.Head() || len(neg.L.Events) != len(full.L.Events) {
		t.Errorf("EngineAt(-1) head %s (%d events), full replay head %s (%d events)",
			neg.L.Head(), len(neg.L.Events), full.L.Head(), len(full.L.Events))
	}
	if neg.L.Head() != meta.Head {
		t.Errorf("EngineAt(-1) head %s is not the capture point (recorded %s)", neg.L.Head(), meta.Head)
	}
}

// TestReproOnFreshSnapshot runs the whole product on a snapshot captured
// live by the feedback capture's own code in this test — not the committed
// fixture — so the loader cannot drift from the capture shape without this
// failing. The corpus pin coupling the committed fixture carries does not
// apply here: the capture and the replay run against the same corpus.
func TestReproOnFreshSnapshot(t *testing.T) {
	requireCorpus(t)
	advance, r := gatedFixtureRegistry(t)
	advance(12)
	dir := t.TempDir()
	captureSnapshotFiles(t, r, dir)

	var out bytes.Buffer
	if code := run([]string{dir}, &out, io.Discard); code != 0 {
		t.Fatalf("exit %d, output:\n%s", code, out.String())
	}
	if !strings.Contains(out.String(), "replayed 21 of 21 recorded intents") {
		t.Errorf("fresh snapshot summary unexpected:\n%s", out.String())
	}
	out.Reset()
	if code := run([]string{"-list", dir}, &out, io.Discard); code != 0 {
		t.Fatalf("list exit %d, output:\n%s", code, out.String())
	}
}

// TestReproEmitTestSkeletonCompilesAndFailsOnTODO: -emit-test copies the
// snapshot into the target package's testdata and writes a test that
// compiles and fails only on its TODO. The target is a scratch package
// under the repo root (a real package the go tool builds), removed on
// cleanup.
func TestReproEmitTestSkeletonCompilesAndFailsOnTODO(t *testing.T) {
	requireCorpus(t)
	root, err := feedback.Root()
	if err != nil {
		t.Skipf("no repo root: %v", err)
	}
	scratch := filepath.Join(root, "zzrepro-emittest")
	t.Cleanup(func() { os.RemoveAll(scratch) })
	if err := os.MkdirAll(scratch, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(scratch, "doc.go"), []byte("package emittmp\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	var out bytes.Buffer
	if code := run([]string{"-emit-test", "zzrepro-emittest", fixtureRel}, &out, io.Discard); code != 0 {
		t.Fatalf("emit exit %d, output:\n%s", code, out.String())
	}
	if _, err := os.Stat(filepath.Join(scratch, "testdata", "feedback", fixtureID, "match.json")); err != nil {
		t.Errorf("snapshot not copied: %v", err)
	}

	// The generated test is the target package's EXTERNAL test package —
	// feedback imports the engine tier, so an internal-package skeleton
	// would be an import cycle for any engine-side target. The declaration
	// (not the file name) is what makes it external.
	san := sanitize(fixtureID)
	raw, err := os.ReadFile(filepath.Join(scratch, "repro_feedback_"+san+"_test.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(raw), "package emittmp_test") {
		t.Errorf("generated skeleton is not the external test package:\n%s", raw)
	}

	// The generated test compiles and fails on its TODO, not on load.
	cmd := exec.Command("go", "test", "./zzrepro-emittest", "-run", "TestFeedbackRepro20260914T120000Z_fb01")
	cmd.Dir = root
	raw2, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("generated test passed; it must fail on the TODO:\n%s", raw2)
	}
	if !strings.Contains(string(raw2), "TODO: assert the reported behaviour") {
		t.Fatalf("generated test failed for another reason:\n%s", raw2)
	}
}

// TestReproEmitTestIntoRulesCompilesAndFailsOnTODO is the probe the scratch
// package cannot be: the NATURAL target for a repro test is an engine
// package (the reported behaviour lives in rules/), and an internal-package
// skeleton emitted there forms rules -> feedback -> rules — an import cycle
// the go toolchain refuses at setup. The skeleton is the external test
// package, so emitting into the real rules package must compile and fail
// only on the TODO. The file (and its copied snapshot) is removed on
// cleanup; the run compiles the rules test binary from the build cache
// because nothing in rules changed.
func TestReproEmitTestIntoRulesCompilesAndFailsOnTODO(t *testing.T) {
	requireCorpus(t)
	root, err := feedback.Root()
	if err != nil {
		t.Skipf("no repo root: %v", err)
	}
	san := sanitize(fixtureID)
	testPath := filepath.Join(root, "rules", "repro_feedback_"+san+"_test.go")
	dataDir := filepath.Join(root, "rules", "testdata", "feedback", fixtureID)
	// Only remove what this test created: rules/testdata is not ours if it
	// already carried content before the emit.
	testdataPreExisting := false
	if ents, err := os.ReadDir(filepath.Join(root, "rules", "testdata")); err == nil && len(ents) > 0 {
		testdataPreExisting = true
	}
	t.Cleanup(func() {
		os.Remove(testPath)
		os.RemoveAll(dataDir)
		if !testdataPreExisting {
			os.Remove(filepath.Join(root, "rules", "testdata", "feedback"))
			os.Remove(filepath.Join(root, "rules", "testdata"))
		}
	})

	var out bytes.Buffer
	if code := run([]string{"-emit-test", "rules", fixtureRel}, &out, io.Discard); code != 0 {
		t.Fatalf("emit exit %d, output:\n%s", code, out.String())
	}
	raw, err := os.ReadFile(testPath)
	if err != nil {
		t.Fatalf("skeleton not written into rules/: %v", err)
	}
	if !strings.Contains(string(raw), "package rules_test") {
		t.Fatalf("skeleton emitted into rules/ is not the external test package:\n%s", raw)
	}
	cmd := exec.Command("go", "test", "./rules", "-run", "^TestFeedbackRepro20260914T120000Z_fb01$")
	cmd.Dir = root
	res, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("emitted rules test passed; it must fail on the TODO:\n%s", res)
	}
	if !strings.Contains(string(res), "TODO: assert the reported behaviour") {
		t.Fatalf("emitted rules test failed for another reason:\n%s", res)
	}
}

// TestReproEmitTestRefusesOverwrite: a second emit at the same target is
// refused rather than clobbering a test someone may have filled in.
func TestReproEmitTestRefusesOverwrite(t *testing.T) {
	requireCorpus(t)
	root, err := feedback.Root()
	if err != nil {
		t.Skipf("no repo root: %v", err)
	}
	scratch := filepath.Join(root, "zzrepro-emittest2")
	t.Cleanup(func() { os.RemoveAll(scratch) })
	if err := os.MkdirAll(scratch, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(scratch, "doc.go"), []byte("package emittmp\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	if code := run([]string{"-emit-test", "zzrepro-emittest2", fixtureRel}, &out, io.Discard); code != 0 {
		t.Fatalf("first emit exit %d:\n%s", code, out.String())
	}
	// Simulate a filled-in test and a hand-refreshed snapshot: the refused
	// second emit must leave both byte-identical, not just exit non-zero.
	san := sanitize(fixtureID)
	testPath := filepath.Join(scratch, "repro_feedback_"+san+"_test.go")
	logPath := filepath.Join(scratch, "testdata", "feedback", fixtureID, "log.json")
	filledTest := []byte("package emittmp_test\n\n// filled in by hand\n")
	editedLog := []byte(`{"edited":"by hand"}`)
	if err := os.WriteFile(testPath, filledTest, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(logPath, editedLog, 0o644); err != nil {
		t.Fatal(err)
	}
	out.Reset()
	if code := run([]string{"-emit-test", "zzrepro-emittest2", fixtureRel}, &out, io.Discard); code == 0 {
		t.Fatalf("second emit overwrote the first:\n%s", out.String())
	}
	if got, _ := os.ReadFile(testPath); !bytes.Equal(got, filledTest) {
		t.Errorf("refused emit rewrote the test file:\n%s", got)
	}
	if got, _ := os.ReadFile(logPath); !bytes.Equal(got, editedLog) {
		t.Errorf("refused emit rewrote the snapshot's log.json:\n%s", got)
	}
}

// TestReproEmitTestRejectsTamperedCapture: -emit-test verifies the complete
// capture before writing. A log.json whose head alone was corrupted exits
// non-zero with DIVERGED and creates neither the snapshot copy nor the
// skeleton.
func TestReproEmitTestRejectsTamperedCapture(t *testing.T) {
	requireCorpus(t)
	root, err := feedback.Root()
	if err != nil {
		t.Skipf("no repo root: %v", err)
	}
	scratch := filepath.Join(root, "zzrepro-emittest3")
	t.Cleanup(func() { os.RemoveAll(scratch) })
	if err := os.MkdirAll(scratch, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(scratch, "doc.go"), []byte("package emittmp\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	dir := tamperFixture(t, func(lg map[string]any) {
		lg["head"] = "deadbeefdeadbeef"
	})
	var out bytes.Buffer
	if code := run([]string{"-emit-test", "zzrepro-emittest3", dir}, &out, io.Discard); code == 0 {
		t.Fatalf("tampered capture emitted with exit 0:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "DIVERGED") {
		t.Errorf("output missing DIVERGED:\n%s", out.String())
	}
	if _, err := os.Stat(filepath.Join(scratch, "testdata")); !os.IsNotExist(err) {
		t.Errorf("tampered emit created testdata (stat err %v)", err)
	}
	if _, err := os.Stat(filepath.Join(scratch, "repro_feedback_"+sanitize(fixtureID)+"_test.go")); !os.IsNotExist(err) {
		t.Errorf("tampered emit wrote the skeleton (stat err %v)", err)
	}
}

// TestReproEmitTestStripsTokenScriptsFromLiveCapture is the ruling's
// boundary for -emit-test on a LIVE capture: the source match.json carries
// the raw token script text (host.FeedbackMatch.Tokens), and the committed
// copy must NOT — Forge token scripts are GPL-3.0 and must never be
// committed. The emitted match.json must carry neither `tokens` nor
// `tokens_unread`, the exact text must be SYNced into the gitignored token
// directory keyed by the fixture id, and the emitted snapshot must still
// replay (resolving its tokens from that sync directory) to the recorded
// head — the round-trip that keeps the sync path honest.
func TestReproEmitTestStripsTokenScriptsFromLiveCapture(t *testing.T) {
	requireCorpus(t)
	root, err := feedback.Root()
	if err != nil {
		t.Skipf("no repo root: %v", err)
	}
	scratch := filepath.Join(root, "zzrepro-stripemittest")
	t.Cleanup(func() { os.RemoveAll(scratch) })
	if err := os.MkdirAll(scratch, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(scratch, "doc.go"), []byte("package striped\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	// A live capture, not the committed fixture: match.json carries tokens.
	advance, r := gatedFixtureRegistry(t)
	advance(12)
	src := t.TempDir()
	captureSnapshotFiles(t, r, src)
	id := filepath.Base(src)
	// -emit-test syncs the stripped token text into the gitignored token
	// directory keyed by this fixture id; remove it on cleanup so the test
	// does not litter that directory with a per-run random id.
	syncDir, err := feedback.TokenSyncDir(id)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { os.RemoveAll(syncDir) })
	srcRaw, err := os.ReadFile(filepath.Join(src, "match.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(srcRaw), "tokens") {
		t.Fatalf("live capture match.json carries no tokens field:\n%.200s", srcRaw)
	}

	var out bytes.Buffer
	if code := run([]string{"-emit-test", "zzrepro-stripemittest", src}, &out, io.Discard); code != 0 {
		t.Fatalf("emit exit %d, output:\n%s", code, out.String())
	}

	emitted := filepath.Join(scratch, "testdata", "feedback", id, "match.json")
	emittedRaw, err := os.ReadFile(emitted)
	if err != nil {
		t.Fatalf("emitted match.json not found: %v", err)
	}
	if strings.Contains(string(emittedRaw), "tokens") {
		t.Errorf("emitted match.json still carries token script text:\n%.300s", emittedRaw)
	}

	// The exact script text went to the gitignored sync directory instead,
	// keyed by the fixture id.
	syncRaw, err := os.ReadFile(filepath.Join(syncDir, "tokens.json"))
	if err != nil {
		t.Fatalf("token sync directory missing: %v", err)
	}
	var synced map[string]string
	if err := json.Unmarshal(syncRaw, &synced); err != nil {
		t.Fatalf("sync tokens.json: %v", err)
	}
	if len(synced) == 0 {
		t.Fatalf("sync directory carried %d token scripts, the capture had more", len(synced))
	}

	// The emitted snapshot resolves its tokens from the sync directory and
	// must still replay to the recorded head — the stripped copy is not a
	// silent no-op.
	l, cfg, meta, err := feedback.Load(filepath.Join(scratch, "testdata", "feedback", id))
	if err != nil {
		t.Fatalf("load emitted snapshot: %v", err)
	}
	ene, err := replay.Replay(l, cfg)
	if err != nil {
		t.Fatalf("replay emitted snapshot: %v", err)
	}
	if got := ene.L.Head(); got != meta.Head {
		t.Errorf("emitted snapshot replayed head %q, recorded %q", got, meta.Head)
	}
}

// TestPrintSeatsShowsOpponentAuraOnItsHost: the view groups battlefields by
// controller, so an Aura seat 0 controls on seat 1's creature sits in seat
// 0's list while its host sits in seat 1's. The summary must print it on the
// host (naming its controller), and not drop it from both sections.
func TestPrintSeatsShowsOpponentAuraOnItsHost(t *testing.T) {
	players := []view.PlayerView{
		{ID: 0, Name: "Caster", Battlefield: []view.CardView{
			{ID: 10, Name: "Pacifism", AttachedTo: 20},
			{ID: 11, Name: "Plains"},
		}},
		{ID: 1, Name: "Target", Battlefield: []view.CardView{
			{ID: 20, Name: "Grizzly Bears", Power: 2, Toughness: 2},
			{ID: 21, Name: "Rancor", AttachedTo: 20},
		}},
	}
	var out bytes.Buffer
	printSeats(&out, players, false)
	got := out.String()
	if !strings.Contains(got, "  - Grizzly Bears (#20) 2/2") {
		t.Errorf("host line missing:\n%s", got)
	}
	if !strings.Contains(got, "    - Pacifism (#10) 0/0 (seat 0's)") {
		t.Errorf("opponent's Aura not rendered under its host with its controller:\n%s", got)
	}
	if !strings.Contains(got, "    - Rancor (#21) 0/0") {
		t.Errorf("own attachment not rendered under its host:\n%s", got)
	}
	// A standalone permanent line starts the line with exactly two spaces;
	// a nested attachment line carries four. Anchor on the newline so a
	// nested "    - Pacifism" cannot be mistaken for a standalone "  - "
	// line (its substring would otherwise match).
	if strings.Contains(got, "\n  - Pacifism") || strings.Contains(got, "\n  - Rancor") {
		t.Errorf("an attachment also printed as a standalone permanent:\n%s", got)
	}
	if !strings.Contains(got, "  - Plains (#11)") {
		t.Errorf("unattached permanent missing:\n%s", got)
	}
}

// TestPrintSeatsKeepsAttachmentWithMissingHost: an attachment whose host is
// not in the view still prints, naming the host id, instead of vanishing.
func TestPrintSeatsKeepsAttachmentWithMissingHost(t *testing.T) {
	players := []view.PlayerView{{ID: 0, Name: "Solo", Battlefield: []view.CardView{
		{ID: 10, Name: "Bonesplitter", AttachedTo: 99},
	}}}
	var out bytes.Buffer
	printSeats(&out, players, false)
	if !strings.Contains(out.String(), "- Bonesplitter (#10) 0/0, attached to #99 (not on the battlefield)") {
		t.Errorf("orphaned attachment not printed:\n%s", out.String())
	}
}

// TestPrintSeatsAttachmentFullDetail is the regression for the review
// finding that a nested attachment was flattened to a name: a tapped
// attachment with counters and damage lost its object id, P/T, tapped
// state, damage and counters, and two same-name attachments became
// indistinguishable. Each attached permanent must carry the full
// characteristics a standalone one would.
func TestPrintSeatsAttachmentFullDetail(t *testing.T) {
	players := []view.PlayerView{
		{ID: 0, Name: "Caster", Battlefield: []view.CardView{
			{ID: 10, Name: "Lightning Greaves", Power: 2, Toughness: 2, Tapped: true,
				Damage: 3, Counters: map[string]int32{"+1/+1": 2}, AttachedTo: 20},
		}},
		{ID: 1, Name: "Target", Battlefield: []view.CardView{
			{ID: 20, Name: "Grizzly Bears", Power: 2, Toughness: 2, Tapped: true},
			{ID: 21, Name: "Lightning Greaves", Power: 2, Toughness: 2, AttachedTo: 20},
		}},
	}
	var out bytes.Buffer
	printSeats(&out, players, false)
	got := out.String()
	if !strings.Contains(got, "    - Lightning Greaves (#10) 2/2, damage 3, tapped, counters +1/+1:2 (seat 0's)") {
		t.Errorf("tapped counter-bearing attachment lost detail:\n%s", got)
	}
	if !strings.Contains(got, "    - Lightning Greaves (#21) 2/2") {
		t.Errorf("same-name attachment not rendered by its own id:\n%s", got)
	}
	if !strings.Contains(got, "  - Grizzly Bears (#20) 2/2, tapped") {
		t.Errorf("host detail missing:\n%s", got)
	}
}

// tamperFixture copies the committed fixture into a temp dir and rewrites
// its log.json through edit.
func tamperFixture(t *testing.T, edit func(map[string]any)) string {
	t.Helper()
	dir := t.TempDir()
	for _, f := range []string{"match.json", "view.json", "report.json"} {
		raw, err := os.ReadFile(filepath.Join(fixtureRel, f))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, f), raw, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	raw, err := os.ReadFile(filepath.Join(fixtureRel, "log.json"))
	if err != nil {
		t.Fatal(err)
	}
	var lg map[string]any
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber() // preserve the uint64 seed exactly while editing another field
	if err := dec.Decode(&lg); err != nil {
		t.Fatal(err)
	}
	edit(lg)
	out, err := json.Marshal(lg)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "log.json"), out, 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

// cutTailFixtureRel is the second committed fixture: the REAL
// fb-20260915T094418Z capture — a vs-bot Commander match parked mid-burst
// on the CR 903.9 commander_zone ask, recorded by the pre-fix host. Its
// log.json is the legacy capture shape: trimmed to the last burst's ask
// boundary (1324 events) while its head field was taken over the FULL
// chain (1326 events — the burst's post-ask tail, two real events, which
// the trim cut). The replay of the recorded intents reconstructs the tail;
// the chain proves it byte-exact, so the capture verifies and exits 0.
const cutTailFixtureRel = "testdata/feedback/20260915T094418Z-e484f1db"

// TestReproCutTailCaptureExitsZero: the CLI on the parked-burst capture
// verifies the head — reconstructed tail included — and prints the summary,
// exiting 0. This is the regression for repro's own half of
// fb-20260915T094418Z: the same capture used to exit 1 with a spurious
// "replay diverged at event 1324" the moment the replay ran past the trim.
func TestReproCutTailCaptureExitsZero(t *testing.T) {
	requireCorpus(t)
	var out bytes.Buffer
	if code := run([]string{cutTailFixtureRel}, &out, io.Discard); code != 0 {
		t.Fatalf("exit %d, output:\n%s", code, out.String())
	}
	for _, want := range []string{
		"== feedback report 20260915T094418Z-e484f1db",
		"replayed 249 of 249 recorded intents (1326 events)", // the two reconstructed tail events included
		"recorded head",
		"pending: seat 0 commander_zone",
		"Valgavoth, Harrower of Souls would go to the graveyard: put it into the command zone instead?",
	} {
		if !strings.Contains(out.String(), want) {
			t.Errorf("summary output missing %q:\n%s", want, out.String())
		}
	}
}

// tamperCutTailFixture is tamperFixture pointed at the second fixture (its
// match.json is already token-stripped, so a copied temp dir resolves its
// tokens through the live corpus — the fresh-clone path, which replays).
func tamperCutTailFixture(t *testing.T, edit func(map[string]any)) string {
	t.Helper()
	dir := t.TempDir()
	for _, f := range []string{"match.json", "report.json"} {
		raw, err := os.ReadFile(filepath.Join(cutTailFixtureRel, f))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, f), raw, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	raw, err := os.ReadFile(filepath.Join(cutTailFixtureRel, "log.json"))
	if err != nil {
		t.Fatal(err)
	}
	var lg map[string]any
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	if err := dec.Decode(&lg); err != nil {
		t.Fatal(err)
	}
	edit(lg)
	out, err := json.Marshal(lg)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "log.json"), out, 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

// TestReproCutTailCaptureRejectsATamperedHead: the cut-tail tolerance is
// the chain, not a blind pass. A capture of exactly the legacy shape whose
// head field no longer chains to the replayed stream (here: head altered)
// still reports DIVERGED and exits non-zero — the reconstructed tail is
// accepted only when it is proven byte-exact.
func TestReproCutTailCaptureRejectsATamperedHead(t *testing.T) {
	requireCorpus(t)
	dir := tamperCutTailFixture(t, func(lg map[string]any) {
		lg["head"] = "deadbeefdeadbeef"
	})
	var out bytes.Buffer
	if code := run([]string{dir}, &out, io.Discard); code == 0 {
		t.Fatalf("tampered head exited 0:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "DIVERGED") {
		t.Errorf("output missing DIVERGED:\n%s", out.String())
	}
}

// TestReproCutTailCaptureRejectsATamperedRecordedEvent: a corrupted event
// inside the RECORDED prefix still diverges at that event, named — the
// tolerance never widens into the recorded region.
func TestReproCutTailCaptureRejectsATamperedRecordedEvent(t *testing.T) {
	requireCorpus(t)
	dir := tamperCutTailFixture(t, func(lg map[string]any) {
		evs := lg["events"].([]any)
		e := evs[len(evs)-1].(map[string]any) // the recorded DecisionAsk at the trim point
		if e["kind"] != json.Number("20") {
			panic("fixture's last recorded event is not the ask (kind 20)")
		}
		e["text"] = "tampered"
	})
	var out bytes.Buffer
	if code := run([]string{dir}, &out, io.Discard); code == 0 {
		t.Fatalf("tampered event exited 0:\n%s", out.String())
	}
	got := out.String()
	if !strings.Contains(got, "DIVERGED") || !strings.Contains(got, "diverged at event") {
		t.Errorf("output missing the divergence:\n%s", got)
	}
}

// TestEngineAtLoadsTheCutTailCapture: feedback.EngineAt — the entry a
// -emit-test skeleton calls — replays the same legacy capture to every
// recorded intent, tolerance and all, so a test bootstrapped from this
// capture reaches the parked board instead of failing on the trim.
func TestEngineAtLoadsTheCutTailCapture(t *testing.T) {
	requireCorpus(t)
	e := feedback.EngineAt(t, cutTailFixtureRel, -1)
	if len(e.L.Events) != 1326 {
		t.Fatalf("EngineAt produced %d events, want the full 1326 (tail reconstructed)", len(e.L.Events))
	}
	d := e.Pending()
	if d == nil || d.Kind != "commander_zone" {
		t.Fatalf("pending is %+v, want the parked commander_zone ask", d)
	}
}
