// TypeScript twins of package protocol (github.com/adams-shaun/gorge/protocol).
// Regenerate with `make gentypes`; `make lint` fails when this file is stale.
// Code generated by cmd/gentypes; DO NOT EDIT.

export type FrameType = "hello" | "widget" | "match_start" | "snapshot" | "event" | "decision" | "match_end" | "table_halted" | "overflow" | "error" | "rewind";

export type MatchState = "live" | "finished" | "aborted" | "crashed";

export type Mode = "overview" | "focus";

export type Phase = "beginning" | "main1" | "combat" | "main2" | "ending" | "";

export type StackKind = "spell" | "ability" | "trigger";

export type TableState = "idle" | "live" | "cooldown" | "halted";

export type Visibility = "seat" | "public" | "omniscient";

  /**
   * Frame is the envelope. ID is the session-wide frame counter and the SSE
   * id; 0 means "not resumable" (widgets). Table/Match/Seq locate the body in
   * a match's chain: Seq is the engine's own event sequence, the number the
   * hash chain covers.
   */
export interface Frame {
  v: number;
  t: string;
  id?: number;
  table?: string;
  match?: number;
  seq: number;
  body: unknown;
}

  /**
   * TableInfo is one row of the overview.
   */
export interface TableInfo {
  id: string;
  name: string;
  seats: number;
  spectator: string;
  state: string;
  match: number;
  perpetual: boolean;
  /**
   * Format is the table's construction format, "constructed" or
   * "commander" (host.Format.String()). Always emitted: the zero
   * Format is "constructed", a real value, so an omitted field
   * would be indistinguishable from it.
   */
  format: string;
  /**
   * BotPolicy is the effective hosted policy for bot seats and human-seat
   * caretakers. It is public table configuration, never private game state.
   */
  bot_policy: string;
  /**
   * SeatNames names the table's seats in seat order: the deck name each
   * seat is playing, as MatchStart carries them. Empty when no match
   * has started on this table yet. It is public information -- the
   * overview already shows every table's life totals and deck
   * identities in its transcript -- so it is not redacted per viewer.
   * omitempty is right here, unlike Format: an absent list and an empty
   * list mean the same thing (no match yet), so there is no value that
   * omitting would make ambiguous.
   */
  seat_names?: string[];
  /**
   * Mulligans is the table's London mulligan allowance (TableConfig.Mulligans):
   * each player may take up to this many pre-game mulligans. Always emitted,
   * like Format: the zero value is 0, a real value that disables the pre-game
   * round, so an omitted field would be indistinguishable from it. It is
   * public table configuration, never private game state — a restart control
   * reads it to recreate the same game.
   */
  mulligans: number;
}

  /**
   * Hello opens every stream: the session id the client echoes in POSTs and
   * the table list as of now.
   */
export interface Hello {
  session: string;
  tables: TableInfo[];
}

  /**
   * Widget is the overview cell: enough to draw a 2x2 life grid, a turn
   * marker and a stack-depth badge, plus the last transcript line.
   */
export interface Widget {
  turn: number;
  step: string;
  phase: string;
  active: number;
  priority: number;
  life: number[];
  lost: boolean[];
  stack_depth: number;
  last: string;
  state: string;
}

  /**
   * SeatInfo names a seat for the identity bars; Colour is the seat colour
   * the client keeps consistent from overview to focused view. Human marks a
   * seat played by a real person (TableConfig.Humans): additive and omitempty
   * (old sidecars and every bot seat omit it), it is what tells a client
   * whether an undo control may be offered — the registry refuses an undo on
   * any table whose human seats are not all the requester, so a seat that can
   * see two humans on the wire can know its UNDO button would be refused
   * (dispatch fb-20260911T201015Z).
   */
export interface SeatInfo {
  name: string;
  deck: string;
  colour: string;
  human?: boolean;
  /**
   * DeckID is the exact deck id this seat plays — the TableConfig.Decks
   * entry the match loaded (host/match.go's deckNames), NOT the deck's
   * display Name. The two can differ: cmd/gorged's catalogue falls back to
   * the file stem only when a deck file has no Name. A client that restarts
   * the game must post this id back as human_deck/bot_deck; posting the
   * display name would 400 "unknown deck". omitempty matches Human's
   * additive shape.
   */
  deck_id?: string;
}

  /**
   * MatchStart announces match k on a subscribed table.
   */
export interface MatchStart {
  seats: SeatInfo[];
  seed: number;
  spectator: string;
  bot_policy: string;
}

  /**
   * Printing is the identity a client resolves an image by: the exact face
   * name today. Set and Number stay empty until a printing table exists
   * (roadmap open question 1); the fields are here so the wire shape does
   * not change when it does.
   */
export interface Printing {
  name: string;
  set?: string;
  number?: string;
}

  /**
   * ManaProduction is a face's mana-production capability summary, expressed
   * as plain data so any later package (view, botpolicy, the seat adapter) can
   * carry it without importing a package to its right. It is derived from the
   * face's own abilities -- never from land subtypes. A face with several mana
   * abilities lists their possible production here; rules selects exactly one
   * when a shared tap cost is paid (rules/mana_activation.go).
   *
   * Colour is indexed the same way state.Mana is (W, U, B, R, G, then
   * colourless), so a caller that also imports state can translate an index
   * with state.ManaIndex. A dual land may list both possible colours here, but
   * selecting one of its distinct mana abilities on activation adds only that
   * selected ability's mana.
   *
   * Any reports that at least one mana ability's Produced$ was not a plain
   * colour string: "Any"/"Combo Any", a listed "Combo X Y" choice, or a
   * "Chosen"/"Special" word (any token the symbol grammar cannot read). Such a
   * source is conditional in the card script, so a policy must not treat it as
   * a dependable colour fixer. Colour carries what a plain token names (one each
   * for "R G", two for "RR") and the real alternatives of a choice token. It
   * never counts letters of script words as phantom mana: Chosen is represented
   * by all five possible colours because its source-specific choice is not
   * available to this source-free parser.
   */
export interface ManaProduction {
  colour: [number, number, number, number, number, number];
  any: boolean;
}

  /**
   * CardView is one object's public face: printed identity plus its current,
   * derived characteristics. Nothing here is read from a hidden zone unless
   * the viewer owns it — cardViews is only ever called with a zone list the
   * caller has already decided is visible.
   */
export interface CardView {
  id: number;
  name: string;
  face_down?: boolean;
  types: string;
  /**
   * ManaCost is the printed cost in Forge's notation ("1 W", "R", "X G").
   * Hand lists render it as symbols.
   */
  mana_cost?: string;
  /**
   * SpellAPI is the API of the card's primary cast-shape ability (its
   * SP$ line -- "Counter" for Counterspell, "DealDamage" for Lightning
   * Bolt, "" for a card with no spell ability, which is every creature
   * and every activated-ability permanent). It is a printed card fact,
   * projected for exactly the cards the projection already carries the
   * printed ManaCost and Types of -- a visible card's own text is open
   * information -- so a seat that can read a card's cost can read what
   * the cast does at the same grain. The bot policy's casting rule reads
   * it (carried into botpolicy.Card.Counter) to tell a counter spell
   * from any other cast. A hidden hand's cards are never projected as
   * CardViews at all, so this never leaks hidden information.
   */
  spell_api?: string;
  /**
   * Printing is what an image lookup keys on; Token ("#12") tells two
   * copies of one card apart in the stack, the log and an arrow.
   */
  printing: Printing;
  token: string;
  /**
   * AttackingPlayer is the seat this creature is attacking while
   * Attacking is true, nil otherwise; BlockedBy lists the creatures
   * blocking it. Both exist for the arrow overlay (PL-17) and come
   * straight from the object's combat fields, which EndCombatReset clears.
   */
  attacking_player?: number | null;
  blocked_by?: number[];
  tapped: boolean;
  power: number;
  toughness: number;
  damage: number;
  attacking: boolean;
  counters?: Record<string, number>;
  keywords?: string[];
  /**
   * Controller and Owner can differ (a stolen permanent, a stack object
   * created for someone else's turn); a client needs both. Battlefield
   * zone lists are keyed by controller, every hidden/graveyard/exile list
   * by owner (events/apply.go's zoneOwner), so a CardView carries both
   * regardless of which zone list it came from.
   */
  controller: number;
  owner: number;
  summon_sick: boolean;
  /**
   * AttachedTo is the permanent this Aura or Equipment is currently
   * attached to, 0 meaning unattached -- the same zero-value convention
   * Obj uses, so omitempty keeps an unattached permanent (or a non-
   * permanent: a spell, a card in a hand) from emitting a field. It comes
   * straight from state.Object.AttachedTo, which the engine's Attach event
   * sets and clears; without it a client could not render an attachment
   * beneath the permanent it modifies -- could not tell what is attached
   * to what at all.
   */
  attached_to?: number;
  /**
   * ActivatedThisTurn is how many non-mana activated abilities of this
   * object were activated this turn (events.Apply's AbilityPush census on
   * state.Object.ActivatedThisTurn). Public fact, like the tap state it
   * rides beside; the bot policy's repeatable-ability budget (A5) reads
   * it to bound its own loop-shaped activations (Basalt Monolith's untap
   * re-enabling its own tap) without ever gating a human seat, for whom
   * unlimited activations stay legal and offered.
   */
  activated_this_turn?: number;
  /**
   * AbilityCosts is the current offer-time Forge-notation cost of each
   * non-mana activated ability, in face ability order. Applicable
   * RaiseCost/ReduceCost statics have already been composed exactly as the
   * engine's legal-action gate composes them; this is deliberately not just
   * the printed Cost$. It is projected only for battlefield cards and the
   * viewer's own hand: those are the cards an interactive seat can use to
   * decide whether floating mana would unlock an ability. Other zones leave
   * it nil, rather than turning this into a general rules-text projection.
   */
  ability_costs?: string[];
  /**
   * Produces is what this card's mana abilities add to the pool when a
   * tap-for-mana activation runs them, derived from the compiled abilities
   * (cards.Face.ManaProduction) rather than land subtypes: a basic land's
   * intrinsic {W}, a dual's {W}{U}, an "add any colour" source's five
   * colour alternatives (one unit each, flagged Any -- the colour is chosen
   * when it is tapped, CR 106.1b), a colourless rock's {C}{C}. nil when the card has no mana
   * ability at all, so a creature or a spell never pays for the six-entry
   * array on the wire. It is a projected characteristic like ManaCost and
   * Keywords -- a mana ability's production is a card fact every seat sees,
   * and it is projected for the same zones the card itself is visible in.
   * This is what the bot policy's colour-aware tap and land heuristics read
   * (carried into botpolicy.Card as plain data, never the view type).
   */
  produces?: ManaProduction | null;
}

  /**
   * PoolRestrictionView is one restricted floating-mana batch as the wire
   * sees it: the produced symbol verbatim (a bare WUBRGC letter, an "S<colour>"
   * snow unit or a "<Tag><colour>" typed unit, exactly ManaRestriction.Color),
   * the unit count, and Text -- a sentence naming what the mana may be spent
   * on, or the raw Valid$ string when the formatter does not recognise the
   * shape (an honest floor).
   */
export interface PoolRestrictionView {
  color: string;
  amount: number;
  text: string;
}

  /**
   * PotentialAction is one action a seat COULD take if it first floated every
   * mana its untapped sources could produce: the engine's own legal-offer walk
   * (rules/legal.go) priced against a hypothetical pool instead of the floating
   * one. It is the server-side answer to the float-then-cast payment model --
   * the engine prices a cast against the FLOATING pool only, so the priority
   * window carries no cast option yet, and a client that re-derives
   * "castable after tapping" on its own (printed costs, no live modifiers,
   * no command zone, no flashback) drifts from the engine on every cost rule
   * (Thalia's RaiseCost, a Medallion's ReduceCost, an Indeterminate Tron
   * source, an X spell at 0). The projection carries only what the client's
   * stop decisions need: which kind of action and where its object lives.
   * A card/ability id is NOT a promise the action is currently offered -- it is
   * a promise the engine WOULD offer it once the mana floated.
   */
export interface PotentialAction {
  /**
   * Kind is the action kind, the same vocabulary decision.Option uses but
   * restricted to real plays: "cast", "ability" and "play_land". The mana
   * tap ("activate"), pass and concede are deliberately absent -- they are
   * offered at every priority window and are never a play.
   */
  kind: string;
  /**
   * Obj is the card or permanent the action names (the spell to cast from
   * hand/command zone/graveyard, or the source of the ability), 0 when the
   * action has no object. The id is the CardView id the client already has.
   */
  obj?: number;
  /**
   * Ability anchors an "ability" potential action to its exact activated
   * ability, the index into the source Face().Abilities, exactly as
   * Option.Ability does. omitempty: casts and land drops carry no field.
   */
  ability?: number;
  /**
   * Mode distinguishes a "cast" potential action's payment kind ("",
   * "kicked", "surged", "flashback", "miracle"), exactly as Option.Mode
   * does. omitempty: an ordinary cast carries no field.
   */
  mode?: string;
  /**
   * Label is the offer label ("Cast X", "Name: ability text") -- the same
   * string the corresponding Option would carry, so a client can surface
   * the action without re-deriving it. omitempty: never empty in practice,
   * but a defensive omit keeps the wire free of empty strings.
   */
  label?: string;
}

  /**
   * PlayerView is one seat's own public state, plus (only when this is the
   * viewer's own seat) the private parts.
   *
   * ID's tag is "seat", not "id": state.PlayerID and state.ObjID are both
   * small integers, and this package's own leak test proves the collision is
   * real -- a four-seat board's low ObjIDs (the very first cards dealt) land
   * in the same 0-3 range as every PlayerID, so an "id" tag here would make a
   * CardView's object id and a PlayerView's seat number indistinguishable by
   * key name alone.
   */
export interface PlayerView {
  seat: number;
  name: string;
  life: number;
  lost: boolean;
  library_size: number;
  hand_size: number;
  graveyard_size: number;
  /**
   * LibraryTop is the player's own library's top card, revealed only when
   * a live Continuous MayLookAt grant covers it (Oracle of Mul Daya's
   * "play with the top card of your library revealed") and only to that
   * player's own seat -- the CR 400.2 hidden-zone redaction the Hand field
   * documents applies to it in full. nil (an omitted JSON key) for every
   * other seat and whenever no grant is live.
   */
  library_top?: CardView | null;
  /**
   * Hand is nil (marshalling to a literal JSON null, not an omitted key --
   * it deliberately carries no "omitempty" tag) for every seat but the
   * viewer's own, whose Hand is always non-nil even when empty ("[]").
   * omitempty cannot express "present but possibly empty": with it, the
   * viewer's own EMPTY hand would have marshalled identically to another
   * seat's HIDDEN one (the key simply missing either way), which is exactly
   * the ambiguity this type exists to avoid everywhere else (Winner's own
   * *PlayerID is the same shaped fix). null-vs-[] is what a client checks
   * instead. Hand is a hidden zone under CR 400.2 and stays gated on "is
   * this the viewer's own seat", unlike Pool (next field), which is public.
   */
  hand: CardView[];
  battlefield: CardView[];
  graveyard: CardView[];
  exile: CardView[];
  /**
   * Pool is the mana currently floating in this player's pool. It is
   * PUBLIC information under the CR: a mana pool is not one of the seven
   * zones in CR 400.1 and holds no cards, so CR 400.2's hidden-zone
   * framework (library and hand) has no purchase on it; instead CR 106.4a,
   * 106.4b, 117.3d and 118.3a all require a player to ANNOUNCE what is in
   * their pool, an obligation that is incoherent for information meant to
   * be hidden. So Pool is projected for every seat under every visibility
   * (seat, public, omniscient), like Available. It is always non-nil, even
   * when empty ("{}"), because there is no longer a hidden state to
   * distinguish: an empty pool is simply "{}". The field carries no
   * omitempty, so it is always present even when zero -- the one wire
   * distinction it keeps against Available (which carries omitempty and is
   * absent when nothing is available).
   */
  pool: Record<string, number>;
  /**
   * PoolRestrictions annotates Pool: one entry per batch of floating mana
   * whose producing ability carried a RestrictValid$ spend limit, naming
   * the colour, the amount and a human-readable spend text. It exists
   * because Pool alone renders a bare spendable-looking chip for mana a
   * cast may in fact refuse (Cavern of Souls' {B} that pays only for a
   * creature spell of the chosen type), leaving the seat unable to learn
   * why no cast was offered. Like Pool it is public information -- the
   * restriction is derived from a public battlefield permanent's own
   * ability (CR 106.4a/106.4b), so it is projected for every seat under
   * every visibility. It carries omitempty: a seat holding no restricted
   * mana is absent, never a JSON null, so every view without a restriction
   * serialises byte-identically to before this field existed (the
   * Available convention). A batch whose Valid is empty -- an
   * AddsNoCounter$-only batch, which imposes no spend limit -- is omitted:
   * this field names spend restrictions, and such a batch has none.
   */
  pool_restrictions?: PoolRestrictionView[];
  /**
   * PotentialActions is this seat's "what could I still do after tapping
   * out" projection, filled ONLY for the viewer's own seat (the walk reads
   * the seat's own hand, command zone and graveyard -- a CR 400.2 hidden
   * zone, so another seat's would leak it). Empty/nil means the engine
   * would offer nothing the seat could pay for even after floating every
   * untapped source: the auto-pass stop decision reads this field and
   * nothing else, so it inherits the engine's own cost rules (live
   * RaiseCost/ReduceCost, commander tax, command-zone and flashback casts,
   * X priced at 0, indeterminate sources) instead of a client-side
   * re-derivation of them. It carries omitempty: a seat with no potential
   * actions is absent, like Available.
   */
  potential_actions?: PotentialAction[];
  /**
   * Available is what this player could produce right now by tapping
   * untapped permanents' free-to-tap mana abilities — the "free mana one
   * gains by tapping lands or other effects" half of the seat box's line
   * 3. It is derived from the battlefield (public), so it is filled for
   * every seat under every visibility (seat, public, omniscient), never
   * gated on "is this the viewer's own seat". It is always non-nil, even
   * when empty ("{}"), like Pool. It is separate from Pool on purpose — a
   * reader must never mistake mana that could be tapped for mana already
   * floating.
   * It carries omitempty (so an empty availability is absent, never a JSON
   * null): Available is a public quantity that is only ever present-when-
   * nonzero. Pool, in contrast, carries no omitempty and is always present
   * as an object. This mirrors the sibling CmdDamage field, another public
   * per-player map that is omitted when zero rather than sent as {}.
   */
  available?: Record<string, number>;
  /**
   * Command is the command zone (CR 903.6): the player's commanders
   * currently sitting there, in zone order. A commander leaves it when it
   * is cast (the object itself moves; its id is stable), so Command is the
   * ever-shrinking subset of Commanders that can still be cast from the
   * command zone under the CR 903.8 tax. Public for every seat -- ZCommand
   * is not a hidden zone, and commander identity is open information.
   */
  command: CardView[];
  /**
   * Commanders is the player's full commander roster -- the same list
   * m30's genesis built, in the same order, never shrunk as commanders
   * are cast or die. A roster CardView projects the commander's CURRENT
   * zone's state (a cast commander is a battlefield object, a dead one a
   * graveyard object), so the roster is what lets a client -- and the bot
   * policy's view-shaped half -- tell that a battlefield creature is a
   * commander (the CR 903.10 clock's subject) even when it has left the
   * command zone and not yet dealt damage. Public for every seat: the
   * identity of a player's commanders is the premise of the format.
   */
  commanders: CardView[];
  /**
   * CommanderCasts runs parallel to Commanders: entry k is how many times
   * Commanders[k] has been cast from the command zone, the CR 903.8 tax
   * base for its next command-zone cast (an additional {2} per prior
   * cast). Public for every seat -- the count is derived from public
   * events.
   */
  commander_casts: number[];
  /**
   * CmdDamage is the commander damage this player has taken (CR 903.10),
   * keyed by each commander's object id -- the 21-damage clock, public
   * for every seat like a life total. nil/absent when the player has
   * taken no commander damage (omitempty: absence is zero), so a
   * Constructed game never pays for a per-player empty map.
   */
  cmd_damage?: Record<string, number>;
}

  /**
   * TargetView is one chosen target: exactly one of Obj and Player means
   * anything, discriminated by IsPlayer — the same shape as state.Target.
   */
export interface TargetView {
  obj?: number;
  player: number;
  is_player: boolean;
  /**
   * Label is what the object was allowed to target, in the card's own
   * words: its TgtPrompt$ when it has one ("Select any target"), else its
   * ValidTgts$ ("Creature"). Empty when the object declares neither.
   */
  label?: string;
}

  /**
   * StackView is one object on the stack. Kind is "spell", "trigger" (an
   * object minted by a TriggerPush) or "ability" (any other ability object).
   */
export interface StackView {
  id: number;
  kind: string;
  name: string;
  text: string;
  controller: number;
  source?: number;
  /**
   * Targets is a public list (Ruling T23-u): non-nil, "[]" not "null",
   * even when nothing has been targeted yet.
   */
  targets: TargetView[];
  card?: CardView | null;
  /**
   * Optional and Decider are Ruling VW-1: an optional triggered ability on
   * the stack, awaiting its resolution-time yes/no (CR 603.5), reports that
   * it is optional and names the seat that answers it. Decider is nil
   * unless Optional.
   */
  optional: boolean;
  decider?: number | null;
}

  /**
   * PendingView is a trigger that will hit the stack once its controller has
   * ordered it / its decider has accepted it. R3.
   */
export interface PendingView {
  source: number;
  controller: number;
  label: string;
  optional: boolean;
  decider?: number | null;
}

  /**
   * Option is one legal choice. Obj and Player are echoed only so a client can
   * highlight the object; selection is by Index.
   */
export interface Option {
  index: number;
  kind: string;
  label: string;
  obj?: number;
  /**
   * Counter identifies the counter kind for wildcard counter-removal costs.
   * It is omitted for choices that do not select a counter kind.
   */
  counter?: string;
  /**
   * Player is always emitted because 0 is a valid seat (0-indexed), unlike
   * Obj where 0 means "no object".
   */
  player: number;
  /**
   * Attacker tells a block option's client which attacker this blocker
   * would block, so a human can see the pairing an in-process bot already
   * can (the declare-blockers step is otherwise guessing). omitempty
   * mirrors Obj: an ObjID of 0 means "no object", so an option that has
   * no attacker (any non-block option) emits no field.
   */
  attacker?: number;
  /**
   * Battle, on an attacker option, names the non-player permanent being
   * attacked -- a CR 310.7 battle or a planeswalker -- 0 meaning a player
   * attack. Obj is the attacking creature and Player is the permanent's seat
   * (the battle's protector, or the planeswalker's controller), so the pair
   * alone cannot tell a permanent attack from a player attack by the same
   * creature; this field is what the engine reads back at declaration time to
   * record Object.AttackingBattle. omitempty: a player attack emits no field,
   * so every existing option list serialises byte-identically.
   */
  battle?: number;
  /**
   * Required marks an attacker option whose creature MUST attack this
   * combat (CR 508.1d): a goaded creature (CR 701.38) or one under an
   * unconditional MustAttack static. A rules-ignorant client needs the
   * flag because the engine REJECTS a declaration that omits a required
   * creature it could have included (validateAttackDeclaration) -- an
   * omission that looks legal on the wire otherwise. omitempty: a
   * non-required option emits no field, so every existing option list
   * serialises byte-identically.
   */
  required?: boolean;
  /**
   * MinBlockers/MaxBlockers are the CR 509.1a MinMaxBlocker bounds on the
   * ATTACKER this block option names (Min$ N: the attacker can be blocked
   * only by 0 or at least N creatures; Max$ N: by at most N; both set)
   * together for Min$ All, where the attacker must be blocked by every
   * legal blocker). They exist for the same reason Required does: the
   * engine REJECTS a whole-declaration count outside the bounds
   * (validateMinMaxBlockers), so a rules-ignorant client -- the bot
   * policy included -- needs the bound on the wire to answer legally.
   * Both are omitted for an unbounded attacker, so every ordinary option
   * list serialises byte-identically.
   */
  min_blockers?: number;
  max_blockers?: number;
  /**
   * Group is an exclusivity marker: two options carrying the SAME non-empty
   * Group are mutually exclusive, and at most one of them may be selected
   * in a single answer. The whole contract is that sentence -- it says
   * nothing about blockers, creatures or combat, which is exactly so a
   * rules-ignorant client may enforce it without learning any rules. A
   * client that sees the player pick an option whose Group is already
   * represented in the picked set naturally REPLACES the previously picked
   * option from that group (moving a blocker from one attacker to another
   * should just work) rather than refusing the click. No two options of
   * one Group may be selected together, which Decision.Validate enforces as
   * a general rule.
   */
  group?: string;
  /**
   * AltCostIndex says which cost a "cast" option pays: 0 is the card's own
   * (RaiseCost/ReduceCost-adjusted) cost, i+1 is alternativeCosts(p, id)[i]
   * -- an AlternativeCost static's cost instead -- so a client can show
   * which of several costs the option pays. An "ability" option uses the
   * same field for the same purpose: 0 is the ability's printed Cost$, 1 is
   * its own AlternateCost$ rider (rules/activate.go's abilityAlternateCost,
   * the K:Equip expansion's fourth colon field), so an equip offering its
   * alternate cost is distinguishable from the printed-cost option without
   * parsing the label. omitempty mirrors Obj: an
   * option paying the card's own cost (the common case, and the default
   * every other Option literal in the tree relies on) carries no field, so
   * today's payloads are unchanged for it.
   */
  alt_cost_index?: number;
  /**
   * CostLife is a block option's non-mana life component (CR 509.1b): the
   * life the defender pays for declaring this block, beside Value's mana
   * (the MaxSum budget's currency). A rules-ignorant client sums it
   * against the defender's life total the same way. omitempty: an
   * uncharged option emits no field, so every ordinary option list
   * serialises byte-identically.
   */
  cost_life?: number;
  /**
   * CostTaps is a block option's total tapXType obligation: how many
   * permanents declaring this block taps. The engine resolves the exact
   * permanents deterministically (rules' blockTapPlan), so a client that
   * cannot see the eligible pool -- the shipped bot policy included --
   * treats a positive value as an obligation it cannot verify and declines
   * the option rather than submit a declaration the validator may reject.
   * omitempty as CostLife.
   */
  cost_taps?: number;
  /**
   * Mode distinguishes a "cast" option's payment kind: "" the card's own
   * cost, "kicked", "surged", "flashback", "miracle" -- what the engine
   * reads in beginCast's switch. A client renders a kicked/surged/
   * flashback/miracle cast differently from an ordinary one instead of
   * parsing the label for a keyword. omitempty: an ordinary cast (Mode "")
   * carries no field.
   */
  mode?: string;
  /**
   * Amount is the X value an "x" choose option represents. The option's
   * Index is its position in the list, not its value (see rules/cast.go's
   * xAsk), so without this field a client could not tell "X = 4" from
   * "X = 1" without rereading the label. omitempty: only x options carry
   * it, and on an x option a missing field is exactly X = 0 (the one value
   * that omits), which the option's own label "X = 0" already shows.
   */
  amount?: number;
  /**
   * Ability anchors an "ability" option to its exact activated ability:
   * the index into the source Face().Abilities being offered (Task 10), so
   * a client can pop that ability's own text up beside the right ability
   * on the card. The engine reads it in beginActivation, where a stale
   * index degrades to a no-op. omitempty: options that are not ability
   * options carry no field, and on an ability option a missing field is
   * index 0 (the first ability), the one value that omits.
   */
  ability?: number;
  /**
   * SVar anchors a "granted" option (rules/speed.go, the kw:Start your
   * engines max-speed static's AddAbility$): the SVar name on the source
   * face whose AB the activation resolves through. A granted ability is
   * not a Face().Abilities index (the ordinary "ability" anchor), so it
   * carries the name instead; beginGrantedActivation re-resolves it, so a
   * stale name degrades to a no-op. omitempty: only granted options carry
   * it.
   */
  svar?: string;
  /**
   * Keyword anchors an "ability" option whose body a DERIVED keyword line
   * grants (CR 613.1f): a layer-6 `AddKeyword$ Cycling:1 U` /
   * `AddKeyword$ TypeCycling:Sliver:3` static (Tectonic Reformation,
   * Rhet-Tomb Mystic, Jo Grant, Homing Sliver) gives a hand card a cycling
   * ability no printed face carries, so neither the Ability index nor the
   * SVar name anchors it -- the option carries the keyword line itself
   * ("Cycling:1 U"), which beginActivation synthesizes the ability body
   * from, exactly the SVar-anchor shape with the line standing in for the
   * name. omitempty: only keyword-granted options carry it, so every
   * existing option list serialises byte-identically.
   */
  keyword?: string;
  /**
   * Cost is the activation cost of a priority-window "activate" option whose
   * mana ability costs MORE than a bare tap, in the same whitespace-delimited
   * Forge notation AbilityCosts uses (rules/mana.go's formatCost over
   * ParseCost of the ability's Cost$ param) — "T Sac<1/Lion's Eye Diamond>"
   * for Lion's Eye Diamond, "T PayLife<1>" for Mana Confluence. It is the
   * wire marker the client's empty-priority-window floor and auto-pass need
   * (fb-20260917T192520Z-26136705): isActionKind excludes every "activate"
   * because a bare tap is offered at every window and is not a play, but a
   * costly activation is exactly the play a ritual-combo deck needs the
   * window for, and an empty hand leaves it the window's ONLY action — the
   * floor passed it away unseen, and the card was unreachable for the rest
   * of the game. A bare tap (every plain land) omits the field, so every
   * existing option list and every plain-land window serialises
   * byte-identically. omitempty: only a beyond-tap activation carries it.
   *
   * An "ability" option (a printed non-mana activated ability) carries its
   * offer-time cost here too, the same string the card's AbilityCosts
   * projects: its label is "<card name>: <description>" for every ability
   * of the card, and a planeswalker's description omits the loyalty cost,
   * so the cost is what lets the client's radial tell them apart. Every
   * Cost reader that means the mana-activation marker filters on
   * Kind == "activate".
   */
  cost?: string;
  /**
   * Value is the option's price under a decision carrying a cumulative
   * budget (Decision.MaxSum): a Dig's WithTotalCMC$ cap sums the mana values
   * of the picked cards, so each offered card names its own mana value here
   * -- what lets Decision.Validate enforce "total mana value <= N" over the
   * chosen set without learning what a card is. Zero (mana value 0, or a
   * decision with no budget) omits the field, so every existing option list
   * serialises byte-identically.
   */
  value?: number;
}

  /**
   * DamageEffect describes nominal scripted damage, NEVER guaranteed damage.
   * Prevention, replacement, conditions, division among targets and resolution
   * legality are not evaluated. Spell damage is not commander combat damage.
   */
export interface DamageEffect {
  /**
   * Amount is the nonnegative literal or context-resolved amount at the
   * point the target decision is posed, or nil (JSON null) if it is absent,
   * unresolvable, invalid or outside the supported range. X and SVar
   * expressions are evaluated when the announced/resolving context supplies
   * their value. A known zero is a non-nil pointer to 0. There is deliberately
   * no numeric default: Go consumers must check nil before dereferencing; wire
   * consumers must check null before arithmetic. This is not a lethal-damage
   * claim.
   */
  amount: number | null;
}

  /**
   * RemovalEffect is a conservative classification of an active removal SA.
   * It describes the scripted operation, not whether the target will actually
   * leave at resolution (replacement effects, conditions and legality remain
   * outside a targeting decision). Kind is one of destroy, sacrifice, exile,
   * bounce, graveyard, library or command; Destination is populated for the
   * ChangeZone family and repeats its normalized destination for clients that
   * want the zone rather than the operation.
   */
export interface RemovalEffect {
  kind: string;
  destination?: string;
}

  /**
   * TargetEffect describes only the active SA being targeted, not its parent,
   * sub-abilities or the eventual outcome. API is the compiled primitive name
   * (e.g. DealDamage, Destroy, Counter, Draw). Consumers must treat unfamiliar
   * APIs conservatively; ChangeZone alone does not imply hostile removal.
   * This contains no script text, hidden state or server continuation pointers.
   */
export interface TargetEffect {
  api: string;
  /**
   * Damage is present only for recognised direct damage primitives
   * (DealDamage and DamageAll). Absence is not proof that a whole spell's
   * other abilities cannot deal damage.
   */
  damage?: DamageEffect | null;
  /**
   * Removal classifies the active SA's direct zone-removal shape. It is
   * absent for an unknown API, a non-removal destination, or a ChangeZone
   * whose destination this vocabulary does not model.
   */
  removal?: RemovalEffect | null;
}

  /**
   * Decision is the engine asking one player for one answer.
   */
export interface Decision {
  seq: number;
  player: number;
  kind: string;
  prompt: string;
  min: number;
  max: number;
  options: Option[];
  /**
   * MaxSum, when > 0, is a cumulative budget over the chosen options' Value
   * fields: the sum of the picked options' Value must not exceed MaxSum.
   * The engine's first user is a Dig's WithTotalCMC$ ("put any number of
   * nonland permanent cards with total mana value 4 or less from among
   * them"), which Option.Group's exclusivity cannot express -- a group says
   * "not both of these", a budget says "not all of these". Validate enforces
   * it as one more wire contract, so a rules-ignorant client can grey out an
   * unaffordable pick without summing anything itself. 0 (no budget) omits
   * the field, so every existing decision serialises byte-identically.
   */
  maxSum?: number;
  /**
   * Budgeted marks MaxSum as a PRESENT budget even when it is zero or
   * negative: a MaxSum of 0 alone reads as "no budget" (the omitempty
   * zero), which cannot express a total-power cap of 0 or less
   * (MaxTotalTargetPower$ <= 0, where negative-power options can offset a
   * positive one: powers 2,-1,-1 under a cap of 0 total 0). HasBudget is
   * the one reader; false (the zero) omits the field, so every existing
   * decision serialises byte-identically.
   */
  budgeted?: boolean;
  /**
   * MinSum is the mirror of MaxSum: a cumulative FLOOR over the chosen
   * options' Value fields -- the sum must REACH it, not stay under it. The
   * engine's first user is the tap-cost election of a withTotalPowerGE<N>
   * group predicate (Crew's "tap any number of other untapped creatures
   * you control with total power N or greater", Mossbridge Troll's):
   * Option.Value carries the candidate's current power, and the floor is
   * the whole "total power N or greater" clause. Validate enforces it as
   * one more wire contract, so a rules-ignorant client can grey out an
   * unaffordable pick without learning what power is; FitRequired's repair
   * derives the same floor from this field, never a second copy. Every
   * corpus floor is >= 1, so 0 unambiguously reads as "no floor" and omits
   * the field, keeping every existing decision byte-identical.
   */
  minSum?: number;
  /**
   * GroupLimit caps how many options ONE Group may contribute to an answer:
   * the sum of the picked options sharing a Group must not exceed it. It is
   * the per-type pick count of Forge's EACH multi-type search grammar
   * ("EACH Forest & Plains" with ChangeNum$ 2 finds two Forests and two
   * Plainses), where one Group is one listed type and its cap is ChangeNum --
   * a cap the single-pick exclusivity rule cannot express. 0 or 1 reads as
   * the ordinary at-most-one-per-Group rule, so every existing decision
   * serialises byte-identically and validates unchanged. Validate is the
   * rule's one home; FitRequired and botpolicy's Clamp derive the same cap
   * from GroupCap, never a second copy.
   */
  groupLimit?: number;
  /**
   * GroupLimits maps a Group name to its own selection cap, overriding the
   * decision-wide GroupLimit for that group. A per-defender attack ceiling
   * (AttackRestrict's MaxAttackers$ scoped by ValidDefender$) is exactly
   * this shape: each defended player is its own Group, and two such
   * restrictions can cap different defenders differently, which one scalar
   * GroupLimit cannot express. A group absent from the map, or mapped to a
   * value below 2, falls back to GroupCap. GroupCapFor is the one reader,
   * so Validate, FitRequired and botpolicy's repair cannot drift.
   */
  groupLimits?: Record<string, number>;
  /**
   * Repeatable relaxes Validate's no-duplicate-index rule: when true the
   * SAME option index may be chosen more than once in one answer. It is
   * set only by a modal (Charm) decision whose SA carries
   * CanRepeatModes$ True -- CR 601.2b's "you may choose the same mode more
   * than once" -- where the option list is the distinct modes and the
   * answer is an ordered multiset of them. Every other decision keeps the
   * strict rule. omitempty: a non-repeatable decision carries no field, so
   * every existing payload serialises byte-identically.
   */
  repeatable?: boolean;
  /**
   * Source names the object this decision resolves for -- the spell whose
   * {X} is being chosen, the card whose "as it enters" choice is pending
   * -- so a prompt can always name its source (survey #18) without the
   * client guessing it from the option labels. omitempty mirrors Obj: an
   * ObjID of 0 means "no object", so decisions that do not resolve for a
   * specific object (priority, mulligan, trigger order) carry no field and
   * today's payloads are unchanged for them.
   */
  source?: number;
  /**
   * TargetEffect is host-independent targeting context. It is absent on
   * other decision kinds and on older servers; absent means unknown.
   */
  target_effect?: TargetEffect | null;
  /**
   * Restable marks a KArrange ask whose answer MAY carry Intent.Rest -- the
   * player-chosen order for pile B, the complement of the chosen set. Set
   * only by the scry/surveil ask (effLookAndArrange), whose pile B can be
   * non-empty AND observably ordered (CR 701.17's "in any order" for both
   * piles). An ask without the flag still ACCEPTS a well-formed Rest
   * (Validate's partition rule is kind-generic), but a client should not
   * send one it was not offered -- for a Min == Max == N ask the only valid
   * Rest is empty, so the flag is how a rules-ignorant client knows the
   * second list exists. omitempty: every decision a client sees today
   * serialises byte-identically.
   */
  restable?: boolean;
}

  /**
   * View is one seat's complete picture of the game: everything public, plus
   * whatever is theirs alone (their hand, their mana pool, a decision asked of
   * them).
   */
export interface View {
  viewer: number;
  /**
   * Visibility names which rule set built this view: "seat", "public" or
   * "omniscient" (see Visibility).
   */
  visibility: string;
  /**
   * Turn is the engine's per-player-turn counter (TurnChange events). It
   * increments once per seat's turn, so a four-seat table reads "Turn 22"
   * after five and a half rounds. Round is the exact round-trip count of the
   * players still alive, folded over the ordered event stream (RoundOf) by
   * host, which has the log in hand when it builds this view; a caller with
   * only a snapshot gets the roundOf approximation instead. Both Turn and
   * Round are sent because the raw engine counter is what the transcript
   * ("Turn N: <player>") refers to, and the round is what the board's
   * clock shows.
   */
  turn: number;
  round: number;
  step: string;
  phase: string;
  active: number;
  priority: number;
  over: boolean;
  draw: boolean;
  /**
   * Winner is nil unless Over && !Draw: PlayerID's zero value is seat 0, a
   * real seat, so a bare PlayerID field could never distinguish "seat 0
   * won" from "the game is still going" or "it was a draw" (Task 22
   * finding 5). A JSON null is unambiguous where a bare 0 would not be.
   */
  winner: number | null;
  /**
   * Players, Stack and Pending (below) are every public list this type
   * carries. All of them are built non-nil even when empty (Ruling
   * T23-u): a client should never have to treat a bare JSON `null` and an
   * empty `[]` as the same "nothing here" case for one of these, the way
   * it legitimately must for Hand/Pool below.
   */
  players: PlayerView[];
  /**
   * Stack keeps g.Stack's own order: index 0 is the bottom, the last
   * entry is the top. Public for every seat — R3.
   */
  stack: StackView[];
  /**
   * Pending is the trigger queue, in the order it will be placed on the
   * stack. Public for every seat — R3.
   */
  pending: PendingView[];
  decision?: Decision | null;
}

  /**
   * Snapshot is the whole view at Head plus the turn-start seqs so far — the
   * DVR's scrub ticks.
   */
export interface Snapshot {
  view: View;
  turn_starts: number[];
  head: number;
  /**
   * Seats is the live match's seat list, the same []SeatInfo MatchStart
   * carries. A focus subscriber (host/session.go's Subscribe) receives a
   * snapshot but not the match's match_start frame — that went out before
   * it connected — so without this the table route has no way to learn the
   * seats for the current match (ui16). Always populated for a live match;
   * never omitempty, so the client type stays a plain SeatInfo[].
   */
  seats: SeatInfo[];
}

  /**
   * Event is events.Event for the wire: the same fields, with Kind, zones and
   * step as their names. Zone and step names are set only for the kinds that
   * carry them, so a Tap never reads as "from library". events.Event's own
   * JSON is untouched — it is what the .events file holds.
   */
export interface Event {
  seq: number;
  kind: string;
  player: number;
  obj?: number;
  from?: string;
  to?: string;
  amount?: number;
  step?: string;
  counter?: string;
  text?: string;
  ids?: number[];
  pairs?: [number, number][];
  secret?: boolean;
}

  /**
   * EventBody is one redacted event with its transcript line.
   */
export interface EventBody {
  event: Event;
  line: string;
}

  /**
   * DecisionBody says who is being asked what; options come with the player
   * seat (M2b), not here.
   */
export interface DecisionBody {
  player: number;
  kind: string;
  prompt: string;
}

  /**
   * MatchEnd closes a match: Result is "win" or "draw"; Winner is null for a
   * draw; Head is the chain head the .events file replays to.
   */
export interface MatchEnd {
  result: string;
  winner: number | null;
  head: string;
}

  /**
   * TableHaltedBody is spec D15: a crashed table stops and says why.
   */
export interface TableHaltedBody {
  reason: string;
}

  /**
   * Overflow is the last frame on a stream whose session channel filled.
   */
export interface Overflow {
  dropped: number;
}

  /**
   * ErrorBody is every error reply and the error frame. Head is set only on
   * a 409 "seq beyond head" reply: the last valid seq, so a client can clamp.
   */
export interface ErrorBody {
  code: string;
  message: string;
  head?: number;
}

  /**
   * MatchInfo is one row of a table's match list, from its sidecar.
   */
export interface MatchInfo {
  table: string;
  match: number;
  seed: number;
  seats: SeatInfo[];
  state: string;
  result?: string;
  winner: number | null;
  head?: string;
  events: number;
  turns: number;
  bot_policy: string;
}

  /**
   * Subscribe and Unsubscribe are the POST bodies.
   */
export interface Subscribe {
  session: string;
  table: string;
  mode: string;
}

export interface Unsubscribe {
  session: string;
  table: string;
}

  /**
   * Intent is a client's answer.
   */
export interface Intent {
  seq: number;
  player: number;
  choices: number[];
  /**
   * Rest is the answer's order for the COMPLEMENT of Choices — the second
   * ordered list a KArrange answer may carry (the pile-B order): the options
   * the player did not choose, in the order the player wants them, where
   * "where they go" is still the decision's shared Option.Kind (bottom,
   * graveyard, ...). Absent or empty means the legacy contract: the
   * complement is taken in the order the options were OFFERED. The two lists
   * together must be a partition of the offered options -- Rest's indices
   * are in range, distinct, disjoint from Choices, and
   * len(Rest) == len(Options) - len(Choices) -- which Decision.Validate
   * enforces (one rule, one home: validateRest). Every non-arrange kind
   * rejects a non-empty Rest outright. omitempty: every intent a client
   * sends today serialises byte-identically, and a recorded intent's Rest
   * rides the log and replays exactly (Ruling P2 submits intents as
   * logged).
   */
  rest?: number[];
}
