// TypeScript twins of package protocol (github.com/adams-shaun/gorge/protocol).
// Regenerate with `make gentypes`; `make lint` fails when this file is stale.
// Code generated by cmd/gentypes; DO NOT EDIT.

export type FrameType = "hello" | "widget" | "match_start" | "snapshot" | "event" | "decision" | "match_end" | "table_halted" | "overflow" | "error";

export type MatchState = "live" | "finished" | "aborted" | "crashed";

export type Mode = "overview" | "focus";

export type Phase = "beginning" | "main1" | "combat" | "main2" | "ending" | "";

export type StackKind = "spell" | "ability" | "trigger";

export type TableState = "idle" | "live" | "cooldown" | "halted";

export type Visibility = "seat" | "public" | "omniscient";

export interface Frame {
  v: number;
  t: string;
  id?: number;
  table?: string;
  match?: number;
  seq: number;
  body: unknown;
}

export interface TableInfo {
  id: string;
  name: string;
  seats: number;
  spectator: string;
  state: string;
  match: number;
  perpetual: boolean;
}

export interface Hello {
  session: string;
  tables: TableInfo[];
}

export interface Widget {
  turn: number;
  step: string;
  phase: string;
  active: number;
  priority: number;
  life: number[];
  lost: boolean[];
  stack_depth: number;
  last: string;
  state: string;
}

export interface SeatInfo {
  name: string;
  deck: string;
  colour: string;
}

export interface MatchStart {
  seats: SeatInfo[];
  seed: number;
  spectator: string;
}

export interface Printing {
  name: string;
  set?: string;
  number?: string;
}

export interface CardView {
  id: number;
  name: string;
  types: string;
  mana_cost?: string;
  printing: Printing;
  token: string;
  attacking_player?: number | null;
  blocked_by?: number[];
  tapped: boolean;
  power: number;
  toughness: number;
  damage: number;
  attacking: boolean;
  counters?: Record<string, number>;
  keywords?: string[];
  controller: number;
  owner: number;
  summon_sick: boolean;
  attached_to?: number;
}

export interface PlayerView {
  seat: number;
  name: string;
  life: number;
  lost: boolean;
  library_size: number;
  hand_size: number;
  graveyard_size: number;
  hand: CardView[];
  battlefield: CardView[];
  graveyard: CardView[];
  exile: CardView[];
  pool: Record<string, number>;
}

export interface TargetView {
  obj?: number;
  player: number;
  is_player: boolean;
  label?: string;
}

export interface StackView {
  id: number;
  kind: string;
  name: string;
  text: string;
  controller: number;
  source?: number;
  targets: TargetView[];
  card?: CardView | null;
}

export interface PendingView {
  source: number;
  controller: number;
  label: string;
  optional: boolean;
  decider?: number | null;
}

export interface Option {
  index: number;
  kind: string;
  label: string;
  obj?: number;
  player: number;
  attacker?: number;
  alt_cost_index?: number;
  mode?: string;
  amount?: number;
  ability?: number;
}

export interface Decision {
  seq: number;
  player: number;
  kind: string;
  prompt: string;
  min: number;
  max: number;
  options: Option[];
  source?: number;
}

export interface View {
  viewer: number;
  visibility: string;
  turn: number;
  step: string;
  phase: string;
  active: number;
  priority: number;
  over: boolean;
  draw: boolean;
  winner: number | null;
  players: PlayerView[];
  stack: StackView[];
  pending: PendingView[];
  decision?: Decision | null;
}

export interface Snapshot {
  view: View;
  turn_starts: number[];
  head: number;
}

export interface Event {
  seq: number;
  kind: string;
  player: number;
  obj?: number;
  from?: string;
  to?: string;
  amount?: number;
  step?: string;
  counter?: string;
  text?: string;
  ids?: number[];
  pairs?: [number, number][];
  secret?: boolean;
}

export interface EventBody {
  event: Event;
  line: string;
}

export interface DecisionBody {
  player: number;
  kind: string;
  prompt: string;
}

export interface MatchEnd {
  result: string;
  winner: number | null;
  head: string;
}

export interface TableHaltedBody {
  reason: string;
}

export interface Overflow {
  dropped: number;
}

export interface ErrorBody {
  code: string;
  message: string;
  head?: number;
}

export interface MatchInfo {
  table: string;
  match: number;
  seed: number;
  seats: SeatInfo[];
  state: string;
  result?: string;
  winner: number | null;
  head?: string;
  events: number;
  turns: number;
}

export interface Subscribe {
  session: string;
  table: string;
  mode: string;
}

export interface Unsubscribe {
  session: string;
  table: string;
}

export interface Intent {
  seq: number;
  player: number;
  choices: number[];
}
